### ISSUE TITLE
beta_proportion functions documented but not exposed?

### ISSUE THREAD

**Issue by pboesu** [stan-dev/stan#2765] opened 2019-06-04 10:07 UTC
#### Summary:
Functions `beta_proportion` and `beta_proportion_lpdf` are documented but appear to be not avalaible/exposed in rstan 2.18.2
(Possibly related to this issue: https://github.com/stan-dev/stan/issues/2616)

#### Description:
The Stan 2.18 documentation [descibes a Beta proportion PDF](https://mc-stan.org/docs/2_18/functions-reference/beta-proportion-distribution.html) available as `beta_proportion` and the corresponding `_lpdf` etc. functions.

However, using a sampling statement 
`survival_prop ~ beta_proportion(survival_prop_latent, obs_error_phi );` leads to the error 
```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

Probability function must end in _lpdf or _lpmf. Found distribution family = beta_proportion with no corresponding probability function beta_proportion_lpdf, beta_proportion_lpmf, or beta_proportion_log
```
and using the corresponding lpdf 
`target += beta_proportion_lpdf(survival_prop | survival_prop_latent, obs_error_phi );` leads to a parser error 
```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

No matches for: 

  beta_proportion_lpdf(real[], real[], real)

Function beta_proportion_lpdf not found.
```

An equivalent model using the `beta` function works, so I'm fine to work with that for my application. I just wanted to check whether the availability of the `beta_proportion` in RStan is a known issue, given https://github.com/stan-dev/stan/issues/2616 is an open issue in the stan repo.

#### RStan Version:
packageVersion('rstan')
[1] ‘2.18.2’

#### R Version:
> R.version.string
[1] "R version 3.5.1 (2018-07-02)"

#### Operating System:
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

**Comment by bob-carpenter** [comment] 2019-06-04 15:55
I believe @seantalts has declared all issues on the old language won't-fix pending the new parser release, so I'll leave this one to him to manage with respect to the stanc3 repo.

**Comment by seantalts** [comment] 2019-06-04 18:54
This issue isn't `wont-fix` - the old compiler is :P Made an issue to track this here: stan-dev/stanc3#148

**Comment by bob-carpenter** [comment] 2019-06-04 18:59
I'm confused by the context and all the negations.  @seantalts---can you please either:

* mark this issue (in stan-dev/stan) won't fix and close it, or

* assign it to me to fix

**Comment by seantalts** [comment] 2019-06-04 19:01
Why those two options? Closing this as wont-fix seems misleading to me, especially once we merge repos or try to see which issues still exist on stan 2 vs. stanc3.

**Comment by bob-carpenter** [comment] 2019-06-04 19:15
I read an open issue as a request by the project for a fix.  Do you see it differently?  Will you accept a PR that fixes this issue on stan-dev/stan?

The reason I used to be picky about how precise issues were is that we've gotten a lot of PRs that putatively fix issues, only to have to tell the developers that our issues weren't up to date or didn't fully reflect what we wanted.  I understand you're OK with less precise issues, and I'm not picking on the precision of this one.

**Comment by seantalts** [comment] 2019-06-04 19:33
Hmm, okay. I'll close this one and in general sounds like we should have a policy of moving these to stan-dev/stanc3 until we merge all the repos.

**Closed by seantalts** 2019-06-04 19:33 UTC

**Comment by roualdes** [comment] 2019-06-05 00:57
Sorry I couldn't say something here sooner.  The beta_proportion functions were part of the 2.19 release.  

https://github.com/stan-dev/stan/blob/d0656535b697822445a3dfd7248d05f5933db8ad/RELEASE-NOTES.txt#L31 

Might the beta_proportion functions be in the 2.18 documentation because we only have one source of docs, from which both 2.18 and 2.19 documentation is built?

**Comment by seantalts** [comment] 2019-06-05 00:59
oh, interesting question. I think @pboesu was looking at the correct doc for 2.18, but I'm not sure how that was built. tagging @mitzimorris as that's her domain. 

Separately will remove the "wont-fix-till-new-compiler" label from these issues and label them as fixed in 2.19. Thanks!

**Comment by pboesu** [comment] 2019-06-05 14:49
> 
> 
> Sorry I couldn't say something here sooner. The beta_proportion functions were part of the 2.19 release.
> 
> https://github.com/stan-dev/stan/blob/d0656535b697822445a3dfd7248d05f5933db8ad/RELEASE-NOTES.txt#L31
> 
> Might the beta_proportion functions be in the 2.18 documentation because we only have one source of docs, from which both 2.18 and 2.19 documentation is built?

Thanks for the clarification. Using `rstan_2.19.1` and `StanHeaders_2.18.9` the `beta_proportion` functions work as expected.

**Comment by mitzimorris** [comment] 2019-06-05 18:37
> we only have one source of docs

that's by design.

the Functions Reference Manual was converted from latex to markdown sometime between the 2.18 and 2.19 releases.  when generating 2.18 docs I tried to exclude 2.19 features - either I missed some things or else the docs were re-generated later.

**Comment by seantalts** [comment] 2019-06-05 19:02
That one source should be versioned though and needs to line up with Stan releases.
