### ISSUE TITLE
Uniform sampling of finitely-bounded variable in stan 2.10

### ISSUE THREAD

**Issue by YannickJadoul** [stan-dev/stan#1972] opened 2016-07-25 16:34 UTC
#### Summary:
Using cmdstan 2.10.0, uniform sampling of a bounded variable `real<lower=0, upper=1> x;` fails to produce a random sample. The exact same code works in cmdstan 2.8.0, cmdstan 2.9.0 and pystan 2.9.0.

Am I going crazy (possible :wink:), or did something get broken in 2.10?

#### Description:
Something seems to be going wrong in version 2.10.0 of (cmd)stan, if I sample the following model:
```parameters { real<lower=0, upper=1> x; } model { x ~ uniform(0, 1); }```

When I plot a histogram of the generated samples for `x` (given more than enough iteratations: `./test sample num_samples=1000000 num_warmup=10000`), I see the following distribution:
![uniform](https://cloud.githubusercontent.com/assets/8025744/17108777/371a223a-5295-11e6-85c8-c3f49fcdf7a1.png)

The same doesn't happen in cmdstan 2.8.0, cmdstan 2.9.0 or pystan 2.9.0, so I am assuming it has got something to do with version 2.10 of stan:

![uniform3](https://cloud.githubusercontent.com/assets/8025744/17108906/e3113204-5295-11e6-87f6-ed75e7b1adf6.png)
Blue is cmdstan 2.8.0, green is 2.9.0, red is 2.10.0. Exactly the same small model, exactly the same parameters passed on the command line.

#### Reproducible Steps:
```parameters { real<lower=0, upper=1> x; } model { x ~ uniform(0, 1); }``` and compiling with different versions of cmdstan is all it takes to reproduce. (If relevant: my C++ compiler version is `g++ (Ubuntu 5.4.0-6ubuntu1~16.04.1) 5.4.0 20160609`)

#### Current Version:
v2.10.0

**Comment by bob-carpenter** [comment] 2016-07-25 16:49
I verified that this is a problem in RStan 2.10.  And it doesn't matter whether there is the uniform sampling statement or not.

I don't think anything changed with 2.10 with respect to transforms, but we'll look into it.  I assigned this to Daniel because he worked on the refactoring.

**Comment by bob-carpenter** [comment] 2016-07-25 19:34
My guess is that this is missing a Jacobian adjustment somewhere.  We need to check not just the upper and lower bounds, but all the constrained variables.

**Comment by syclik** [comment] 2016-07-25 21:36
I just checked the generated code. There are 9 differences and they're all whitespace differences.

It's either a bug in the transform or the warmup / sampling changes that were introduced for v2.10.

**Comment by bob-carpenter** [comment] 2016-07-25 22:06
It's sampling too far out in the tails on the unconstrained
space.  It can't just be a missing Jacobian because that causes
Stan to run off into space and is really slow.

Any idea if it's producing the same lp__ values as in 2.9?

Also, any ideas how to add tests for this kind of thing?  Ideally,
we should have simple tests of all the constraints.  It'd require
an additional distribution if the uniform is improper.

- Bob

**Comment by davharris** [comment] 2016-07-25 22:22
Re: testing

I remember John D Cook's chapter on testing RNGs having a helpful perspective. I found a copy online here (skip past the table of contents) http://www.johndcook.com/Beautiful_Testing_ch10.pdf

Dave

**Comment by aadler** [comment] 2016-07-25 22:51
If it helps, Luc Devroye's classic is also free online as a bunch of PDFs (See [here](http://luc.devroye.org/rnbookindex.html)). Probably irrelevant, but that histogram looks not too different from a beta with alpha beta < 1 (although it is too bowed and not flat enough in the center).

**Comment by betanalpha** [comment] 2016-07-25 22:52
It's a small inflation that makes for a surprisingly large effect.  I'm still investigating with limited wifi.

**Comment by betanalpha** [comment] 2016-07-26 00:34
Found it.  There's a copy/paste error in the main loop of transition -- right now the code tries to accept the new subtler _twice_ because the accept code was pasted twice (or more accurately, I forgot to delete one version when I added the other). I haven't checked, but I'm guessing this will fix the other problematic model Ben had (smaller stepsizes -> higher acceptance probs where the double check becomes less of a problem).

I'm about to board this flight (and can't get the airport wifi to work anyways) so I'll patch tomorrow when I'm back in London (before the meeting).  If there's more urgency then someone can just delete lines 110-113 in mcmc/hmc/nuts/base_nuts.hpp and then check that it fixes everything.

**Comment by YannickJadoul** [comment] 2016-07-26 10:17
Confirming that removing these 4 lines indeed solves the problem.
Thank you all for the quick replies and solution!

Oh, and keep up the awesome work, of course! I'm becoming kind of a stan fan (if there is such a thing)

**Comment by bob-carpenter** [comment] 2016-07-26 14:39
Thanks --- Andrew's written extensively about testing MCMC
in particular with Cook (Samantha, not John) and Rubin.  John
Cook's chapter focuses on simple univariate situations.

We're testing the _rng functions built into Stan using what
John Cook calls "bucket testing" (i.e., binning followed
by chi-square).  We're not yet testing the covariances
of multivariate generators, and we really need to do that, too.

The difficulty is in the coding and integration.  We need
a better end-to-end testing framework, which is complicated by
the multi-step compile then run on top of MCMC itself being
harder to test than simple MC.

- Bob

**Comment by betanalpha** [comment] 2016-07-26 15:39
https://github.com/stan-dev/stan/blob/feature/stat_valid_test/src/test/stat-validity/stat_valid_test_fixture.hpp

We just need a proper C++ API to call the sampler without using
any of the CmdStan code.

**Comment by aadler** [comment] 2016-07-26 17:14
@bob-carpenter Have you thought about using the probability integral transform for testing?

**Comment by ericnovik** [comment] 2016-07-26 19:45
@YannickJadoul Please, send me your mailing address and the size of your T-Shirt. Stan branded T will shortly be mailed to you. Thanks for uncovering this bug! (If you want specific kind, you can make your selection here: http://mc-stan.spreadshirt.com)

**Comment by bob-carpenter** [comment] 2016-07-26 20:39
I don't even know what that is, at least not by that
name, but the issue is more with integration on the API
side, not the statistical method (see Michael's last post).
We'll be there soon---Daniel's nearly done with the command
refactor that will make this much easier.

- Bob

**Comment by jgabry** [comment] 2016-07-26 22:45
On Tuesday, July 26, 2016, Bob Carpenter <notifications@github.com> wrote:

> I don't even know what that is, at least not by that name,


If you're referring to "probability integral transform" then I think that's
the fancy name for the inverse-CDF method for drawing from a distribution
using draws from a uniform.

>

**Comment by aadler** [comment] 2016-07-26 22:46
See [probability integral transform](https://en.wikipedia.org/wiki/Probability_integral_transform). The quantiles of set of randomly generated observations should be uniformly distributed. So regardless of the generating distribution, if you convert the observations to the corresponding points on the CDF through F^{-1}(X) the resulting values should be uniformly distributed between 0 and 1. It's the inverse of using the CDF to generate observations.

**Comment by aadler** [comment] 2016-07-26 22:47
@jgabry Yes, and it it can be used in the forward direction to test for testing that the numbers are being generated randomly.

**Comment by jgabry** [comment] 2016-07-26 22:56
On Tuesday, July 26, 2016, Avraham Adler <notifications@github.com> wrote:

> @jgabry <https://github.com/jgabry> Yes, and it it can be used in the
> forward direction to test for testing that the numbers are being generated
> randomly.
>
We do something kind of like this in rstanarm (borrowing from Andrew and
Sam Cooke's paper) with the pp_validate function. If we simulate
"true" data from a fitted model and then refit the model using this data,
the quantiles of each "true" parameter wrt its posterior should be
uniformly distributed.

>

**Comment by bgoodri** [comment] 2016-07-27 00:07
The `pp_validate` test does not seem to be especially powerful. And we can't just do what we do for the `_rng` functions because those produce iid samples whereas the MCMC samplers do not. Really, rstanarm --- especially including its demos --- is the biggest collection of end-to-end useages of Stan but we are not checking the output against previous output.

**Comment by jgabry** [comment] 2016-07-27 01:05
On Tuesday, July 26, 2016, bgoodri <notifications@github.com> wrote:

> The pp_validate test does not seem to be especially powerful. And we
> can't just do what we do for the _rng functions because those produce iid
> samples whereas the MCMC samplers do not. Really, rstanarm --- especially
> including its demos --- is the biggest collection of end-to-end useages of
> Stan but we are not checking the output against previous output.
>

Yeah I agree with all of that.

And we probably should be testing against previous output, at least for
some models that run really fast.

>

**Closed** 2016-07-27 04:23 UTC

**Comment by YannickJadoul** [comment] 2016-07-27 08:36
:open_mouth: A Stan t-shirt? Brilliant, I'm already going NUTS about it!
_(sorry, you must've heard that one before, but I couldn't resist)_

On a more serious matter: will you be releasing a version 2.10.1 (or similar) soon? After all, the only reason I managed to find this bug and dug into the results was because I was trying to match up the results of two models, where one analytically marginalized over variables the other was sampling.

**Comment by betanalpha** [comment] 2016-07-27 08:43
Yes, there will be a new release by the end of the week.

**Comment by betanalpha** [comment] 2016-07-27 08:44
Although if you’re using CmdStan, the develop branch has already been fixed.

**Comment by YannickJadoul** [comment] 2016-07-27 08:48
Ok, sounds perfect, thanks.
I solved the problem by just removing the lines you mentioned, but it was just about unsuspecting people possibly getting (slightly) wrong results while doing research.

**Comment by jgabry** [comment] 2016-07-27 19:35
On Wednesday, July 27, 2016, Yannick Jadoul <notifications@github.com>
wrote:

> Ok, sounds perfect, thanks.
> I solved the problem by just removing the lines you mentioned, but it was
> just about unsuspecting people possibly getting (slightly) wrong results
> while doing research.
>
Yeah, we're already in the process of getting the other interfaces updated,
although it will take a few days for StanHeaders + RStan to make it through
the CRAN process.

Fortunately, I've run a bunch of models in RStan and rstanarm for which I
know the results from 2.9 and there doesn't seem to be much of a difference
with 2.10. Of course I only know that for the models I've run but that's at
least encouraging.

Thanks again for catching the bug!

>
