### ISSUE TITLE
unexpected behavior

### ISSUE THREAD

**Issue by howarth** [stan-dev/stan#2657] opened 2018-10-05 21:29 UTC
if `a` is a `vector[N]` then

`target += a`

seems equivalent ("seems" because I just know by testing it) to

`target += sum(a)`

I would expect that instead the first line would throw a compilation error since `target` is a real value and `a` is a vector.

**Comment by bob-carpenter** [comment] 2018-10-08 00:33
This is intended behavior.  It's documented in the reference manual section "Increment Log Density"  in the subjection "Vectorization".

I can see where the expectation of a compilation error would come from and in retrospect, that might have been a better decision since we don't have a lot of operations that produce vectors of log densities.  Nevertheless, we're going to leave it like this for now and I'm going to close this issue.

**Closed by bob-carpenter** 2018-10-08 00:33 UTC
