### ISSUE TITLE
HMC goes into infinite loop

### ISSUE THREAD

**Issue by lazypanda1** [stan-dev/stan#2476] opened 2018-02-23 03:59 UTC
Hi,

When I run the model below with `PyStan`, `NUTS` algorithm converges to some values, but `HMC` goes into an infinite loop. 
```
data {
  int<lower=0> N;
  real datax[N];
  real datay[N];
}

parameters{
  real p1;
  real p2;
}

model {
  p1 ~ gamma(4.12334383145,71.1494061142);
  p2 ~ cauchy(10.9431568035,52.5576747842); 
  for(i in 1:N){
    datay[i] ~ chi_square(abs(floor(p1*datax[i] +p2)));
  }
}

```

In both cases, I am getting this exception several times:

```
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: chi_square_lpdf: Degrees of freedom parameter is 0, but must be > 0!  (in 'unkown file name' at line 14)
```

I expected `HMC` to terminate and report something at least, even if it doesn't converge. Is this expected? Or a known issue? I think it would be helpful if `HMC` terminates with some error message and helps the user debug the issue.

Environment:
```
Pystan 2.16.0.0
Python 2.7.6
```

**Comment by bob-carpenter** [comment] 2018-02-23 16:54
Thanks for getting involve,d @lazypand1.  We try to reserve issues for things that are either bugs or concrete feature requests.  I'm afraid this isn't either.

If you're trying to file a bug report, it helps immensely to provide a reproducible example rather than a synopsis.

I'm not sure what you mean by "infinite loop".  You had to kill the process to stop it from going on forever?  Was it producing any output?  

The message you're getting is about a numerical error.  Unfortunately, floating point is tricky and it's not a bug in the algorithm if there are places where it fails.  So I'm afraid that's about as informative an error message as we can produce.  At that point, you have to start debugging by printing or using the diagnose function.

There are two fundamental problems with this:
```
datay[i] ~ chi_square(abs(floor(p1*datax[i] +p2)));
```
First, the `floor` function breaks the continuous differentiability required for Stan posteriors.  You shouldn't be using it on parameters unless you really know what you're doing with the derivatives.  There are warnings in the manual, but we're trying to scale back on warnings in the code for now to prevent more false positives.  The second problem is `abs`, which introduces a multimodality between `(p1, p2)` and `(-p1, -p2)` (as well as a classical non-identifiability).

Anyway, I'm closing this issue as it's not a bug or a concrete feature request.

**Closed by bob-carpenter** 2018-02-23 16:54 UTC
