### ISSUE TITLE
 optimizing () segfault; regression in stan 2.5

### ISSUE THREAD

**Issue by segasai** [stan-dev/stan#1216] opened 2015-01-13 15:00 UTC
Hi, I've noticed that 2.5 version of stan segfaults on a very simple model when I run optimizing(). When I revert back to 2.4 segfault doesn't happen. Here is a simplified test case (demonstrated using pystan, but as far as I understand it also occurs with the R-backend). 

```
data {
	int Npm;
}

transformed data {
	vector[2] mu_obs;
	matrix[2,2] coverr;
	vector[2] tmp;
	mu_obs[1] <- 0;
	mu_obs[2] <- 0;
    tmp[1] <- 1;
    tmp[2] <- 1;
    coverr <- diag_matrix(tmp);
}

parameters {
	real<lower=0,upper=10> ra0;	
}

model {
	vector[2] mu_mod;
	mu_mod[1] <- 0;
	mu_mod[2] <- 0;
    mu_obs ~ multi_normal( mu_mod, coverr );
}
```
Python code:
```python
import pystan
import numpy as np
data = {}
data['Npm'] = 2
sm = pystan.StanModel(model_code=open('model.stan').read())
init = {'ra0':1}
res=sm.optimizing(data=data,init=init,iter=10000)
```

Here is the gdb backtrace:
```
#0  0x0000000000abfa10 in ?? ()
#1  0x00007fffdf7ab697 in stan::agrad::recover_memory ()
    at /local/koposov/soft/pylib2/lib/python2.7/site-packages/pystan/stan/src/stan/agrad/rev/var_stack.hpp:59
#2  0x00007fffdf8304ec in stan::model::log_prob_grad<true, false, anon_model_1bd4e96ac77cdedfa854c4d026018a2c_namespace::anon_model_1bd4e96ac77cdedfa854c4d026018a2c> (model=..., params_r=std::vector of length 1, capacity 1 = {...}, 
    params_i=std::vector of length 0, capacity 0, 
    gradient=std::vector of length 1, capacity 1 = {...}, msgs=0x7fffecc80ce0)
    at /local/koposov/soft/pylib2/lib/python2.7/site-packages/pystan/stan/src/stan/model/util.hpp:108
#3  0x00007fffdf83cead in stan::optimization::ModelAdaptor<anon_model_1bd4e96ac77cdedfa854c4d026018a2c_namespace::anon_model_1bd4e96ac77cdedfa854c4d026018a2c>::operator() (this=0x7fffffffd140, x=..., f=@0x7fffffffd078, g=...)
    at /local/koposov/soft/pylib2/lib/python2.7/site-packages/pystan/stan/src/stan/optimization/bfgs.hpp:357
#4  0x00007fffdf83d3e4 in initialize (this=0x7fffffffd010, 
    model=<value optimized out>, params_r=<value optimized out>, 
    params_i=<value optimized out>, msgs=0x7fffecc80ce0)
    at /local/koposov/soft/pylib2/lib/python2.7/site-packages/pystan/stan/src/stan/optimization/bfgs.hpp:148
#5  initialize (this=0x7fffffffd010, model=<value optimized out>, 
    params_r=<value optimized out>, params_i=<value optimized out>, 
    msgs=0x7fffecc80ce0)
    at /local/koposov/soft/pylib2/lib/python2.7/site-packages/pystan/stan/src/stan/optimization/bfgs.hpp:417
```

The operating system is RHEL 6.6 with gcc 4.4.7
Stan version 2.5.0.1

Thanks,
       Sergey

PS I originally created a pystan bug, but it is probably a bug in stan itself, so I closed the pystan issue and opened this one.

**Comment by bob-carpenter** [comment] 2015-01-13 21:23
Thanks for filing a report.  This is a duplicate of #1200, so I'm closing this and referencing it there.

**Closed by bob-carpenter** 2015-01-13 21:23 UTC
