### ISSUE TITLE
parser fails when it should not

### ISSUE THREAD

**Issue by wds15** [stan-dev/stan#2607] opened 2018-08-16 18:13 UTC
#### Summary:
The stanc parsers fails to parse a valid Stan program.

#### Description:
This (dummy) program fails to compile:

```
functions {
  real foo(vector data) {
    return data[1];
  }
}
```

The error is 
```
Unexpected open block, missing close block "}" before keyword "data".
 error in '../data.stan' at line 3, column 16
  -------------------------------------------------
     1: functions {
     2:   real foo(vector data) {
     3:     return data[1];
                       ^
     4:   }
  -------------------------------------------------


make: *** [../data.hpp] Error 253
```

#### Reproducible Steps:
See above

#### Current Output:
currently we get errors where we should not.

#### Expected Output:
That is a valid stan program.

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.18.0

**Comment by wds15** [comment] 2018-08-16 18:15
This bug is new since 2.18.0 and it forced me to rename any `data` variable in my functions to something else. That is an odd workaround.

**Comment by mitzimorris** [comment] 2018-09-14 14:00
this bug was introduced in an attempt to better handle the missing close curly brace at the end of a block.  backing out the logic which tries to guess what's going on here.

**Comment by mitzimorris** [comment] 2018-09-26 11:45
Closing this PR because it's not a bug, it's a feature - the parser is doing the right thing here, although the error message is confusing.

The language in the Stan Reference Manual is somewhat unclear, so putting in a suggestion for the next manual:  https://github.com/stan-dev/stan/issues/2552#issuecomment-424684781

**Closed by mitzimorris** 2018-09-26 11:45 UTC
Labels: bug, language
