### ISSUE TITLE
Introduce Writer Callback

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#1361] opened 2015-03-11 21:18 UTC
Refactor internal Stan code to use a writer callback class left for the interfaces to implement.  Using the writer callback everywhere will remove the last traces of cout/cerr from the code (addressing #699) while giving the interfaces complete control over output (addressing #453).
- [ ] #1601: remove unused code
- [ ] #1602: implement writers

**Comment by ariddell** [comment] 2015-03-19 17:52
I appreciate what you're doing here, but it seems a bit hasty (esp. probe_args). It feels like one is inventing a protocol from scratch to communicate key value pairs via strings. At minimum, I think I'd prefer we pick something recognizable (like JSON) -- or do a little bit more work to articulate what are valid types of values and spec it in Protobuf.

I suppose I'd also like to see what the big C++ object approach looks like. I don't have that much time this week, but I'd be willing to give a shot at articulating my ideas in a cmdstan branch like this one.

**Comment by betanalpha** [comment] 2015-03-19 17:56
To be clear, the argument stuff is not new.
probe_args is for automated testing.

**Comment by ariddell** [comment] 2015-03-19 18:36
Hmm.. it would be cool if the branch was referenced here somehow (maybe add "Closes #1361" in the commit?). Here's a commit I was looking at: c68ac51d2edb3fb8e59cbeccdfffa31c1879338d

For Python and R I think it's fair to say that it's much easier to create a (pointer to) a struct (or C++ class) and pass that around than to write a C++ callback.

**Comment by betanalpha** [comment] 2015-03-19 18:38
The callbacks here are just classes that implement
certain functions — they should be straightforward
to implement (see the cout/cerr and stream
implementations that will eventually move to CmdStan).

**Comment by ariddell** [comment] 2015-03-19 20:26
I suppose the argument against having interfaces have to write C++ functions starts like this: it's easier to for interfaces to pass around a pointer or a chunk of bytes without knowing too much about it. In fact, with JSON or protobuf they don't even need to touch C++ code potentially. Having them implement a C++ class with specific properties is a significantly bigger hurdle.

It might be helpful to check out how RStan (and PyStan, more or less) currently deal with getting config and defaults setup:

https://github.com/stan-dev/rstan/blob/master/rstan/rstan/inst/include/rstan/stan_args.hpp

**Comment by bob-carpenter** [comment] 2015-03-19 22:43
If you really don't want to work at the C++ level, it
should be possible to completely rewrite PyStan to follow
Stan.jl and MatlabStan (and my original code for RStan), which
would have the user specify a command-line argument as a string,
write the data out to a file, and then execute a CmdStan process
and then collect up the CSV data.

The major problem with this is that it involves an I/O roundtrip,
but that's not usually a bottleneck.

It solves all of Michael's issues with drift.  And it means you
don't need to write any C++ at all.

It would still mean implementing all the posterior analysis stuff
in Python.  Or you could call the print function in CmdStan and
just show it as a string.  Or you could call the C++, but that'd
put you back in C++ land.

- Bob

**Comment by maverickg** [comment] 2015-03-19 23:04
On Thu, Mar 19, 2015 at 11:36:19AM -0700, Allen Riddell wrote:
> Hmm.. it would be cool if the branch was referenced here somehow (maybe add "Closes #1361" in the commit?). Here's a commit I was looking at: c68ac51d2edb3fb8e59cbeccdfffa31c1879338d
> 
> For Python and R I think it's fair to say that it's much easier to create a (pointer to) a struct (or C++ class) and pass that around than to write a C++ callback.
I also think callback should not be used too much. It adds indirection and inflexibility. 

Jiqiang

**Comment by ariddell** [comment] 2015-03-19 23:16
I think shelling out to call cmdstan is a mistake but my only evidence is that RStan and PyStan are working rather smoothly right now and could be working even more smoothly if the steps outlined in the Stan 3.0 wiki page were carried through (i.e., the Python and R interface/classes need to be refactored).

I suspect Julia would be following the same route as Python and R if the interface could be accessed without C++.

**Comment by bob-carpenter** [comment] 2015-03-20 01:09
I like the callback plan!  It's the right way to
write these kind of interfaces for flexibility.
Jiqiang --- what did you think was inflexible?

It does add a bit of indirection, or more specifically,
infersion of control:

  http://en.wikipedia.org/wiki/Inversion_of_control

How do you propose returning results without something
like a callback?  Were you thinking just getting a protocol 
buffer object as a string or something like a C++ data
structure returned?  Both are heavy compared to callbacks,
which don't produce any long-lived memory overhead, much less
conversions to strings and back, which is really slow.  They
also require all the memory to be buffered up, whereas CmdStan
is going to stream answers to an output stream (typically a file).

I'm having a bit of trouble seeing how we can stay away
from C++ and avoid just calling CmdStan as an independent
process doing everything through files.

- Bob

**Comment by sakrejda** [comment] 2015-03-20 17:12
Are these things really as mutually exclusive as it sounds?  With a consistent C++-level interface which requires callbacks I don't think it would be too hard to write standard callbacks for interfacing with protocol buffers much like Michael wrote some standard ones for working with streams.  At least that's my impression based on the simple tutorials: https://developers.google.com/protocol-buffers/docs/cpptutorial.  That adds that pinch point where interfaces could be standardized without pushing protocol-buffers stuff deep into Stan.  It also gets you around C++ being harder to call than C and if somebody wants to make a high-performance interface they can write custom callbacks in C++.  I'm having a hard time telling if that's over-engineering but I don't think so.

**Comment by bob-carpenter** [comment] 2015-03-21 01:13
All else being equal, I'd prefer not to have a chain of
dominos in the interface --- they're hard to maintain.

Also, if the Protocol Buffer to C++ structure isn't in Stan,
it doesn't solve the interface's problem of not wanting to
write so much C++.

One place where Protocol buffers aren't sufficient is for
interrupts --- we need at least one interface-driven callback
for interrupts so we can stop C++ Stan's looping if the interface
wants to stop.

- Bob

**Comment by bob-carpenter** [comment] 2015-03-21 01:23
> On Mar 20, 2015, at 10:16 AM, Allen Riddell <notifications@github.com> wrote:
> 
> I think shelling out to call cmdstan is a mistake but my only evidence is that RStan and PyStan are working rather smoothly right now and could be working even more smoothly if the steps outlined in the Stan 3.0 wiki page were carried through (i.e., the Python and R interface/classes need to be refactored).

Things are definitely much smoother than they use to be, but we
still face:

* installation issues in PyStan and RStan

* compatiblity of C++ toolchain with RStan issues

* limitations imposed by R and Python w.r.t. C++11, which
  we'd really like to start using for code cleanliness and
  efficiency

* crashing issues in RStan (presumably due to saved state and/or
  RStudio --- nobody can give us a reproducible example, and everyone
  says it doesn't happen in the terminal version of RStan).

Also, a thin wrapper would solve the

* not require any C++ coding on the interface side

* requiring updates to RStan or PyStan with every Stan C++
  release

A very thin wrapper (just passing a string) would mean

* no updates needed at all to interfaces when CmdStan changes


> I suspect Julia would be following the same route as Python and R if the interface could be accessed without C++.

See Rob's response.

- Bob

**Comment by ariddell** [comment] 2015-03-21 15:53
Hi Bob,

On 03/20, Bob Carpenter wrote:
> All else being equal, I'd prefer not to have a chain of
> dominos in the interface --- they're hard to maintain.
>

I agree, but the potential gains of having an extremely smooth
installation experience (via install.packages or "pip install pystan")
could trump this, I think. I realize there are some R packages that
compile and call external programs (topicmodels comes to mind, which I
think compiles and runs GibbsLDA++), but this approach is less common in
Python.

> Also, if the Protocol Buffer to C++ structure isn't in Stan,
> it doesn't solve the interface's problem of not wanting to
> write so much C++.

This reflects my thinking as well.

> One place where Protocol buffers aren't sufficient is for
> interrupts --- we need at least one interface-driven callback
> for interrupts so we can stop C++ Stan's looping if the interface
> wants to stop.
>

I'm perfectly fine with the callback here. It happens that the callback
can be in C -- which is nice for (future) interfaces that do not have
support for interfacing with C++.

**Comment by ariddell** [comment] 2015-03-21 16:08
It has occurred to me that it would be helpful if we had some examples of other software projects that deal with similar problems. Clearly Google has solved the problem by passing around Protocol Buffers for everything. But closer to home (i.e., scientific computing) is the Juypter/IPython project, which is a bit like RStudio but supports working with Octave, R, Julia, and Python. Here's how it works: http://ipython.org/ipython-doc/3/development/how_ipython_works.html

Basically IPython exposes ZeroMQ sockets and passes around everything with JSON. It's easy to appreciate that this makes interoperability trivial for any language that supports JSON and ZeroMQ (i.e., everything). Of course, in principle it's not too far removed from the Google approach. It's also pretty slow.

That this discussion is taking time makes perfect sense to me. Up until this point there hasn't been much/any effort to coordinate development between R/Py/CmdStan when that coordination involved more than 2 people.

Perhaps it would be helpful if I added more details to an alternative that avoided callbacks to the Wiki page? I'd also like to hear with @maverickg thinks about all of this.

**Comment by ariddell** [comment] 2015-03-21 16:09
(in response to @bob-carpenter's earlier comment; github needs threaded issue discussions!)

I don't mind updating PyStan every release of Stan (especially if library path renaming is kept to a minimum).

Here's Rob's comment from the list:

"As far as Julia and today’s Stan.jl are concerned, for Julia 0.3.x Allen’s earlier comment about following R and Python without C++ is correct. As alternatives folks can also fall back to RCall.jl and/or PyCall.jl."

**Comment by bob-carpenter** [comment] 2015-03-22 02:05
Replying to two mails from Allen at once:

...

> I agree, but the potential gains of having an extremely smooth
> installation experience (via install.packages or "pip install pystan")
> could trump this, I think. I realize there are some R packages that
> compile and call external programs (topicmodels comes to mind, which I
> think compiles and runs GibbsLDA++), but this approach is less common in
> Python.

Many R packages compile and run extern C, C++ or Fortran
code.  The obstacle presented by Stan is that we need to
compile each model at runtime.  

So that smoothe installation is only going to happen for
Stan for someone who has a recent enough C++ compiler installed.

...

> Perhaps it would be helpful if I added more details to an alternative that avoided callbacks to the Wiki page? I'd also like to hear with @maverickg thinks about all of this.

That would be helpful to me at least.

- Bob

**Comment by ariddell** [comment] 2015-03-24 01:19
Added to the wiki a sketch of how the `command` function would work in a
Protocol Buffer world:

https://github.com/stan-dev/stan/wiki/Stan-API-Refactor#command-with-protocol-buffers

Let me know what you think.

**Comment by bob-carpenter** [comment] 2015-03-25 00:00
I don't think passing C++ objects is a problem --- we're
connecting to them directly in C++, not trying to serialize
as in protocol buffers.

As popular as protocol buffers are at Google (not an uncorrelated
set of independent choices to use protocol buffers), are they used 
to communicate between C++ programs in memory (the way PyStan and
RStan link to Stan) or just for serialized for transport via file or 
socket? 

We looked at something like JSON, and it's very heavy to have
structure per parameter group because of all the added brackets.  
Right now, we're just passing the parameter values for a draw as 
an unstructured array, the downside of which is that it needs to
be translated back to structure for the extractors (at least in RStan).

- Bob

**Comment by ariddell** [comment] 2015-03-25 13:40
My impression is that protocol buffers are used to communicate between distinct *machines* running services written in C++ (or Go). 

Ultimately, I think the reason I'm attracted to Protocol Buffers is because it could make communication to and from Stan easier in a variety of settings (including the case where one machine is compiling and running the model and sending results to another machine). Allowing communication to and from R and Python has been the source of a lot of interesting work recently, including IPython and Shiny.

IPython and Shiny (somehow R and node.js talk to each other, right?) are making scientific computing much more accessible by abstracting (in some cases) away the computer (e.g., you can run IPython and RStudio on an ephemeral cloud server). In this context having some platform-agnostic way of sending and receiving data to and from stan seems like a good goal.

From the meeting yesterday I think we all agreed that the callback method would go forward and then I would be free to try things out on my own using Protocol Buffers and see how much of a performance hit (or gain?) there was.

re: callback method refactoring. I mentioned that I particularly like Bob's `command` function signature in the Wiki. I hope we can eventually get to something that simple.

**Comment by bob-carpenter** [comment] 2015-03-26 00:40
> On Mar 26, 2015, at 12:40 AM, Allen Riddell <notifications@github.com> wrote:
> 
> My impression is that protocol buffers are used to communicate between distinct machines running services written in C++ (or Go).
> 
> Ultimately, I think the reason I'm attracted to Protocol Buffers is because it could make communication to and from Stan easier in a variety of settings (including the case where one machine is compiling and running the model and sending results to another machine). Allowing communication to and from R and Python has been the source of a lot of interesting work recently, including IPython and Shiny.

I guess that need comes up because people want to mix R and Python
packages and neither language has a complete set. 

The danger is robustness and performance from having to write all the
adapters and munge data back-and-forth, but I guess for most of what
people do, neither of these is an issue --- if it were they probably
wouldn't be using R or Python!  R users seem to be happy to just restart
R or RStudio when something crashes.  I think that stems from them primarily
being user-facing front ends rather than back-end servers and so not
requiring any kind of service level agreements. 

> IPython and Shiny (somehow R and node.js talk to each other, right?)

Apparently not very robustly --- Jonah just told me there's a known (or suspected)
bug in R's JSON transport package that causes Shiny apps to hang.  I
unfortunately ran into that one during a demo of shinyStan two days ago.
As soon as things start to break like this, I begin to lose confidence in
them.  (Not an issue with shinyStan yet --- it's still early days there and
I'm not expecting a lot of robustness yet, though I think I'm going to stay
away from live demos until I can convince myself I can do them without freezing. 
It is a major issue with Stan, and we're still struggling with robustness, 
especially across platforms;  it's why we keep prioritizing robustness and
error checking over new features.)

> are making scientific computing much more accessible by abstracting (in some cases) away the computer (e.g., you can run IPython and RStudio on an ephemeral cloud server). In this context having some platform-agnostic way of sending and receiving data to and from stan seems like a good goal.

Agreed.  I just wanted to point out that it's a different goal
than communicating between PyStan and the Stan C++ layer.  We
control both ends of that pipeline.

> From the meeting yesterday I think we all agreed that the callback method would go forward and then I would be free to try things out on my own using Protocol Buffers and see how much of a performance hit (or gain?) there was.

Sounds good --- I think that's the right level of abstraction.
We'd implement some kind of data serialization on top of a 
direct C++ API.  The costs of encoding/decoding are usually
fairly small compared to transport between machines, or even between
disk and back.  

- Bob

**Comment by syclik** [comment] 2015-04-03 14:34
Michael, did you change `interface` to `interface_callbacks`?

**Comment by betanalpha** [comment] 2015-04-03 15:15
I did — I though it was more descriptive and would avoid confusion.

**Comment by syclik** [comment] 2015-04-03 15:17
ok. I merged develop into the branch.

**Comment by syclik** [comment] 2015-05-27 21:49
@betanalpha, were you able to run the unit tests on this branch? I've fixed a handful, but can't get all of it to run.

**Comment by syclik** [comment] 2015-05-27 22:02
@betanalpha, don't worry about it... I'm almost through it, I think.

**Comment by betanalpha** [comment] 2015-05-27 22:30
The tests were all working at my commit, but I haven’t
checked anything after all of the recent merges...

**Comment by syclik** [comment] 2015-05-27 22:42
That's what I was hoping you'd say. I'll get it working.

**Comment by syclik** [comment] 2015-05-28 22:10
Ok, so there was definitely a test that wasn't running --
src/test/unit/mcmc/chains_test.cpp. I've gotten it to compile, but there's
still an issue: the parser() function doesn't like the output generated by
the current version of Stan. Know what's going on?

**Comment by betanalpha** [comment] 2015-05-28 22:42
Or the updated CSV reader doesn’t like static, deprecated
files in the test_csv_files folder?  I’ve hated these tests
from the beginning because they never catch anything
and just require us to change them every f’ing time to
pass.

**Comment by syclik** [comment] 2015-05-29 00:35
This one isn't a false-positive. I just regenerated the test files. I tried
to debug it, but the parse method is just choking.

I'll take an alternative if you have one. You're right: this isn't a really
good way to do a unit test. We need to separate out the file processing
from the chains object, but we don't have a good way to do that right now.

PS. these files haven't changed since Dec 2013. The history before that
isn't easy to get to. If you want to have these generated as part of the
test, let me know. I think I can figure that out. But... I don't think that
really helps, right?

**Comment by betanalpha** [comment] 2015-05-29 08:55
Did you regenerate them with the corresponding cmdstan branch?
It doesn’t look like the test files have the update format, hence
the lexical cast errors.  I’ll try to fix the test later this afternoon.

**Comment by betanalpha** [comment] 2015-05-29 08:59
By the way, at the end of the whole refactor it will be easy to
run models solely through the C++ API allowing us to auto generate
files for tests like these independent of any interface.  The interfaces
can then test their own implementations independently.

**Comment by syclik** [comment] 2015-05-29 11:16
Thanks. I used the latest develop branch: there was still something
incompatible about this branch. If all it takes is to run again, I'll do
that.

**Comment by betanalpha** [comment] 2015-05-29 15:40
Yeah, fixing the format of the output files avoid the read_csv issue.
But all the tests fail because the diagnostics are all slightly off due
to the chains being rerun.  I’ll let you figure out what you want to do
there.

Also, perhaps we might as well move stan_csv_reader to cmdstan
in this pull request?  None of the Stan tests should depend on the
cmdstan output or require that it be run.

**Comment by syclik** [comment] 2015-10-28 22:50
Here are the things that weren't included in stan-dev/stan#1616:
- `src/stan/services/mcmc/warmup.hpp` / `src/stan/services/mcmc/sample.hpp` -> `src/stan/services/sample/run_adaptive_sampler.hpp` / `src/stan/services/sample/run_adaptive_sampler.hpp`
- from CmdStan -> `src/stan/services/diagnose/diagnose.hpp`
- from CmdStan -> `src/stan/services/optimize/optimize.hpp`
- remove: `src/stan/services/io/write_interation_csv.hpp`

I'm leaving this here so I don't forget.

**Comment by bob-carpenter** [comment] 2016-11-24 04:46
@syclik Is this all done and rolled into the refactor?  If so, would you mind closing?

**Comment by bob-carpenter** [comment] 2016-11-24 05:55
This is done.

**Closed by bob-carpenter** 2016-11-24 05:55 UTC
