### ISSUE TITLE
Ternary operator generates C++ code that doesn't compile

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#2044] opened 2016-09-01 01:04 UTC
#### Summary:
The code generator is generating code that doesn't compile. The issue is with the ternary operator.

#### Description:
The C++ that's generated is incorrect. Below is a minimal example.

#### Reproducible Steps:
This Stan program will translate to C++, but not compile.

```stan
transformed parameters {
  real x;
  x = (0 ? x : 0);
}
model {
}
```

There's an explicit cast to `double`, which is causing the failure.

#### Current Output:
Compiler error that looks like (trimmed):
```
In file included from <built-in>:336:
In file included from <command line>:8:
./foo.hpp:129:40: error: cannot convert 'stan::math::var' to 'double' without a conversion operator
            stan::math::assign(x, (0 ? double(x) : double(0) ));
                                       ^~~~~~~~
```

#### Expected Output:
It should compile fine.

Perhaps instead of generating:
```
            stan::math::assign(x, (0 ? double(x) : double(0) ));
```

we can generate:
```
            stan::math::assign(x, (0 ? x : 0 ));
```
?

(I can see how that might be a problem.)

#### Current Version:
v2.11.0

**Comment by bob-carpenter** [comment] 2016-09-01 01:09
That's bad.  Do you want to fix this for the next release?  If so, I can work on it tomorrow because Mitzi's only doing Stan work on the weekends.

The issue is more complicated than the suggested change because of the way the ternary operator resolves mismatched type arguments.

**Comment by syclik** [comment] 2016-09-01 01:11
If you think you can handle it tomorrow or the next day, I'm happy waiting.

**Comment by bob-carpenter** [comment] 2016-09-01 01:12
What needs to happen is that both results need to be explicitly cast to the result type.  I'm not sure how easy it will be to fix because I didn't write that code.  It should've had a unit test for this, so I at least know where to start.

**Comment by bob-carpenter** [comment] 2016-09-01 01:12
Don't we need to get 2.12 out sooner rather than later?

**Comment by syclik** [comment] 2016-09-01 01:12
(and I figured it had to do with mismatched type arguments and I was really
hoping that wasn't the issue.)

**Comment by syclik** [comment] 2016-09-01 01:21
Yes, we need to get 2.12 out sooner. But I think we said we could get it
out within a week. (I might be misremembering.)

Do you want me to put in tests for ternary operator? I'm up now and can put
it on a branch.

**Comment by mitzimorris** [comment] 2016-09-01 05:42
the file stan/src/test/test-models/good/validate_conditional_op_good.stan (incorrectly) contains statements which will tickle this bug in the transformed parameters block, lines 125, 126:

```
  tpy = y < 100 ? y : py;   // t,f : real,var
  tpy = y < 100 ? x : py;   // t,f : int,var
```

generated code validate_conditional_op_good.cpp is:
```
            stan::math::assign(tpy, (logical_lt(y,100) ? y : py ));
            current_statement_begin__ = 126;
            stan::math::assign(tpy, (logical_lt(y,100) ? double(x) : double(py) ));
```

**Comment by bob-carpenter** [comment] 2016-09-01 12:23
That previous comment is behavior on the develop branch and what we would have seen in 2.11.

These are all `real` type variables, and `tpy` is a transformed parameter, `y` and `x` are data, and `py` is declared as a parameter.

The question is why didn't the good models compilation tests pick up that the second line's nested expression `(logical_lt(y,100) ? double(x) : double(py) )` couldn't be compiled because there's no way to evaluate `double(py)`?

**Comment by bob-carpenter** [comment] 2016-09-01 12:24
And by behavior, I mean that the `stan/src/test/test-models/good/validate_conditional_op_good.stan` was already in the set of good test models in 2.11.  

So I think something's broken where the good models aren't being compiled extensively enough to test this.  I'd very much like to get this fixed in case there are other issues like this one lurking in the good models that we don't know about.

**Comment by syclik** [comment] 2016-09-01 12:28
I'll take a look. Maybe an hour or two?

**Comment by bob-carpenter** [comment] 2016-09-01 12:36
I tried sending this via email, but maybe there's lag.  

The real question is why Stan programs that translate to C++ but then don't compile pass tests---I thought we were catching those by trying to compile all of the code generated by models in test/test-models/good.

**Comment by bob-carpenter** [comment] 2016-09-01 12:36
OK.  The real question is why Stan programs that translate to C++ but then don't compile pass tests---I thought we were catching those by trying to compile all of the code generated by models in test/test-models/good.

**Comment by syclik** [comment] 2016-09-01 12:55
Yes. That's exactly what I want to hunt down. It should have been tested,
but perhaps it's not finding all the files?

**Comment by syclik** [comment] 2016-09-01 14:38
So, we have a little trouble with the testing. I thought that compiling it the generated header with this additional option was sufficient:
```
clang++ ... -c -fsyntax-only -O0 src/test/test-models/good/validate_conditional_op_good.hpp
```

The important bit being `-fsyntax-only`. Turns out I'm wrong.

Good news: we're testing all the files the same way.
Bad news: it wasn't sufficient enough testing.

I'll create a new issue for this. I don't want to tangle up this fix with a whole bunch of makefile magic.

**Closed** 2016-09-02 03:42 UTC
