### ISSUE TITLE
Error in overloading user-defined functions

### ISSUE THREAD

**Issue by HerraHuu** [stan-dev/stan#1450] opened 2015-05-14 21:10 UTC
It seems that function overloading is currently broken. Minimal code example (same thing happens with different argument types):

```
functions {        
    int user_fun(int x) {        
        return 1;        
    }        
    int user_fun(real x) {        
        return 1;        
    }        
}
model{ }
```

This raises the following error using RStan v2.60:

*Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! file1ff4863b4a6.cpp:59:8: error: redefinition of ‘struct model1ff4224cbe63_test_namespace::custom_fun1_functor__’
 struct custom_fun1_functor__ {
        ^
file1ff4863b4a6.cpp:39:8: error: previous definition of ‘struct model1ff4224cbe63_test_namespace::custom_fun1_functor__’
 struct custom_fun1_functor__ {
        ^
make:  [file1ff4863b4a6.o] Error 1
In addition: Warning message:
running command '/usr/lib/R/bin/R CMD SHLIB file1ff4863b4a6.cpp 2> file1ff4863b4a6.cpp.err.txt' had status 1*

**Comment by betanalpha** [comment] 2015-05-14 21:21
Function overloading has never worked and we have not
claimed that it works.  See previous threads on this list or
the relevant issues on GitHub.

**Comment by HerraHuu** [comment] 2015-05-14 21:24
Oh, sorry I have missed those threads. In the manual it says : "Stan allows function overloading, where two functions have the same name. For example, an overloaded unit-normal log density function might be declared with an overload of the function unit_normal_log, giving it three signatures with one argument each."

**Comment by betanalpha** [comment] 2015-05-14 21:30
Thanks for pointing that out — that definitely shouldn’t be there
until we can fix the function name mangling on the backend.

**Comment by bob-carpenter** [comment] 2015-05-14 22:20
That was my bad.  You could originally overload functions all you wanted until I added functors.  I think you can probably still overload built-ins exactly once.  I'm modifying the manual (and maybe the parser) to make things consistent.

The issue isn't mangling so much as collecting up all the definitions of a given name and then throwing them all into a single functor as different `operator()` signatures.  Not impossible, but a fair bit of walking over the AST and keeping lists of what's been visited.

I'm closing this issue and have copied it over to the next manual, where I'll fix it:

https://github.com/stan-dev/stan/issues/1420#issuecomment-102185595

**Closed by bob-carpenter** 2015-05-14 22:20 UTC
