### ISSUE TITLE
Enable TLS for the website

### ISSUE THREAD

**Issue by KOLANICH** [stan-dev/stan#2663] opened 2018-10-11 06:27 UTC
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by syclik** [comment] 2018-10-11 14:11
Thanks for reporting. This is a duplicate of stan-dev/stan-dev.github.io#32 (different repo). I'll close this and we can pick it up there.

**Closed by syclik** 2018-10-11 14:11 UTC
