### ISSUE TITLE
warmup fails in some cases

### ISSUE THREAD

**Issue by wds15** [stan-dev/stan#1902] opened 2016-06-01 19:59 UTC
#### Summary:
Warmup seems to fail on some models.

#### Description:
 Behavior may be related to XHMC patches and occurs on a given model for some seeds/chains, but not all chains fail for a given case. The failing chains run very fast with very short warmup but give nonsense results. It appears that with the cmdstan git hashes

- 169c0fb does not work; 17 April
- 27e078f WORKS OK (before the BIG HMC refactor); 26 March

#### Reproducible Steps:
Attached is an example which triggers the ill-behavior for chain 1, but chain 2 runs ok for the current cmdstan. The cmdstan 27e078f version runs ok on chain 1 as well. The parameters which are obviously fail to be estimated are xi_eta and others are not estimated correctly as well (this is simulated data).

#### Current Output:
Chain 2 is ok; chain 1 is not.

#### Expected Output:
chain 1 should statistically match chain 2.

#### Additional Information:
To start each chain, run
SGE_TASK_ID=1 ./fit.sh
SGE_TASK_ID=2 ./fit.sh

#### Current Version:
develop, see above cmdstan hashes which translate to stan hashes. Platform is MacOS X with clang (newest versions as of 1 of June 16).

[testcase.zip](https://github.com/stan-dev/stan/files/294262/testcase.zip)

**Comment by wds15** [comment] 2016-06-03 07:18
It would be great if someone could confirm that the example provided fails with the current cmdstan version for him as well. I will be out of office starting from Monday; so I can only give intermittently feedback on any progress on this one past Monday. The way to confirm would be to run chain 1 and chain 2 with the most up to date cmdstan. Chain 2 should be ok while chain 1 runs way too fast and gives non-sense results. Only the cmdstan git hash noted above as working ok will process chain 1 and 2 correctly.

**Comment by syclik** [comment] 2016-06-06 14:17
@wds15, I've tried to reproduce, but can't. What compiler are you using?

I'm using XCode's built in clang++:

```
> clang++ -v
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

For me, chain 1 and chain 2 using the old version you claimed work take forever to sample. In the newer version, it samples fast for chain 1 and slow for chain 2.

Do you see this happening on any simpler models?

**Comment by wds15** [comment] 2016-06-06 14:50
@syclik You are seeing the problem which I am experiencing, I think. Chain 1 runs on my computer in 5 minutes and gives me non-sense results. Chain 2 gives me the correct results and takes 58 minutes.

So it sounds as if you are running into the problem with chain 1.

My clang++ version is 
```
> clang++ -v
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
```

I can try to reduce the number of patients from 500 to a smaller number for this example, but I am afraid that the problem occurs more often with more patients rather than less. So I don't know if the problem happens with only 50 patients or so, but I can try.

**Comment by wds15** [comment] 2016-06-06 15:13
I tried to reduce the problem size to 100 or 50 patients only, but then everything seems to work just fine. So I am guessing that the dimensionality of the problem must be sufficiently large. Maybe the centered funnel example with ~500 dimensions does the trick; don't have that at hand right now.

I am attaching the log files of chain 1 and chain 2. There you see that chain 1 is not OK by all the nan's for the xi_eta variables which are ok for chain 2.

Checking the csv files from these runs shows that chain 1 has as inverse mass matrix on the diagonal only the number 0.000166667 and nothing else. Chain 2 has a proper mass matrix, i.e. all elements are different.

[logs.zip](https://github.com/stan-dev/stan/files/300693/logs.zip)

**Comment by syclik** [comment] 2016-06-06 15:21
Yes, I am seeing it, but the newer version works and the older version doesn't.

**Comment by bob-carpenter** [comment] 2016-06-06 15:21
If the performance across random seeds is indistinguishable
from or better than the previous release, this shouldn't
prevent releasing.

Of course, we'd all love to have faster and more reliable
adaptation.

- Bob

**Comment by wds15** [comment] 2016-06-06 15:25
No, this is not a performance difference between seeds. The chain 1 fails to do anything useful since adaption of the mass matrix fails. The chain 2 runs ok as adaptation succeeds in finding a mass matrix. The adaptation used to be robust against these sort of things; this fragility is new in the current develop version.

@syclik : Not sure what you mean with "works". The correct results take ~1h on my computer.

**Comment by syclik** [comment] 2016-06-06 15:43
What I'm seeing on my machine:

Old:
Chain 1 takes about 1 hr. 
Chain 2 takes about 1 hr. 

Develop:
Chain 1 takes 3 mins, but has nonsensical results. 
Chain 2 takes 35 mins. (Results look indistinguishable from the old results)


We're not going to tell based on 2 chains with such short warmup. My guess is that if we tan 100 chains, we'd see both the new and old fail for random chains, but the new stuff behaving better overall.

**Comment by wds15** [comment] 2016-06-06 15:53
Yes, I think that describes it well.

The new stuff is faster, but not robust. I haven´t done a big study, but my impression so far is that the larger the dimensionality of the problem, the larger the chances are that things fail. I have to hurry now and have no time now (maybe tom), but I think that the funnel example with increasing dimensionality may be a good candidate to test this hypothesis.

**Comment by betanalpha** [comment] 2016-06-06 20:20
I just landed back in London a few hours ago but it’ll be
some time before I can get to this (averaging about talk a
week for the rest of the summer).  Keep in mind that the
tree building algorithm should not have changed (this was
unit tested) but the way samples were chosen from the trees
was changed.  This should be a small effect, but it will essentially
cause the RNG to reseed which can easily perturb a fragile
model into a pathological state.  If only two chains were run
then I am no where near convinced that the original model 
wasn’t pathological — as Dan notes you’d need many more
chains to make any such claim and hence put the blame on
the sampler itself.

When I get a chance I’ll make sure that the trees are the
same for this particular model (assuming it’s easy enough
to run) but beyond that it will require a lot more work to
validate the model and not the sampler.

**Comment by wds15** [comment] 2016-06-06 23:14
I am just worried here, thats all.

I have seen this odd behavor first on another model at work with multiple chains indeed. So the problem exists for two models and a number of chains - at least for me.

The example i have provided should be ok since this is simulated stuff and i have tested that stan can recover the simulated parameters. Moreover, the very first chain failed! I provided the second to show that things can work. I think youn can just add a bit of noise to the inits or choose a different initial seed and the problem should come with more chains, at least my guess.

Thanks Michael for looking into this.

**Comment by wds15** [comment] 2016-06-07 09:46
It looks like my intuition was right in that a high-dimensional funnel type problem will tickle the issue more reliably. Attached is what can be called a minimal example, I guess. The funnel-hard.R was used to simulate the stan_data.R file. The fit.sh script starts the cmdstan run. With the new code I get for the first ten chains 

```
## chains OK: 1 3 5
## chains NOT OK: 2 4 6 7 8 9 10
```

That is, not OK here means that some theta estimates come out nan. In comparison to that, the old warmup code computes things just fine for all of the chains.

The example is quite extreme in how I have chosen things, so feel free to adapt if needed.

[testcase-funnel.zip](https://github.com/stan-dev/stan/files/302257/testcase-funnel.zip)

**Comment by syclik** [comment] 2016-06-07 14:31
I've just figured out how to push things off to the cluster. On a couple of
models, it looks like adaptation is worse in develop than in v2.9.0. But
those were simple models.

I could run it across all our bugs models, I think.

Mike, any suggestions on how to evaluate this?

**Comment by betanalpha** [comment] 2016-06-07 14:39
First step is to ensure that the tree building is in fact the same,
so that the only difference is the sampling from the tree which
shouldn’t have huge effects.

**Comment by syclik** [comment] 2016-06-07 14:46
Umm.... how would we verify that?

**Comment by betanalpha** [comment] 2016-06-07 14:56
std::cout.  I’m going to see what I can get done before the meeting
as three slide decks in two days is my slide deck create threshold
and I need something else to do.

**Comment by syclik** [comment] 2016-06-07 14:59
Ok. I see. Let me know if you need me to take over at some point. I'll let
you dig into it first. (I won't have a chance until after the meeting.)

**Comment by betanalpha** [comment] 2016-06-07 15:37
I played around with a 10-d funnel model both before and
after, and if you’re careful to correct for how the RNG is
called different before and after (due to the difference 
between slice and Metropolis sampling, etc) then the
trajectories that are built are exactly the same, even as
the trajectories diverge to NaNs.

The only difference is that the slice sampler includes the
slice variable, log_u, in the definition of divergence whereas
there is no such correction in the Metropolis definition of
divergence.  This could cause small changes in the tree 
depth early on in adaptation if the sampler is diverging.
But if the divergences are that bad then it again suggests
that he models were never really fitting all that well in the
first place.

**Comment by syclik** [comment] 2016-06-07 15:40
So... is there any explanation for differences in efficiency (n_eff) for before and after?

**Comment by betanalpha** [comment] 2016-06-07 15:44
No — the problem is that the small differences in how the RNG is 
called almost immediately decouple the chains so the samplers
cannot be compared identically.  I’m looking at the “normal_normal”
model now, but the best I’ll be able to due is try to identify why
adaptation might be failing.

**Comment by syclik** [comment] 2016-06-07 15:53
Yup, everything will be different immediately. 

I was looking at 10 and 100 chains of blocker and bones. In both, the n_eff is higher in the old vs the new. 

I haven't run enough examples to tell if this is generally true.

**Comment by betanalpha** [comment] 2016-06-07 21:15
Okay, I think I found it.

When I calculated the weights I assumed that each new point had
approximately the same energy, if not more due to numerical error,
than the initial point so that I could compute everything on the linear
scale.  This intuition is correct in the typical set, but way out in the tails
it is not unlikely that each new point can have drastically lower energy 
than the first point.  This results in overflowed weights which overflows
the probabilities and forces the sampler to choose the initial point over
and over again.  This results in covariances estimates to be nearly
zero which then gives the pathological mass matrices.

This one is one me — in fact Bob had mentioned that I should be
calculating this on the log scale in the code review.  Jet lag is smacking
me over the head right now, but I’ll switch everything to the log scale
tomorrow morning and see if that fixes the problem, at which point 
Sebastian can see if it fixes all of his examples.

**Comment by bob-carpenter** [comment] 2016-06-08 04:50
> On Jun 7, 2016, at 5:15 PM, Michael Betancourt <notifications@github.com> wrote:
> 
> Okay, I think I found it.
> 
> When I calculated the weights I assumed that each new point had
> approximately the same energy, if not more due to numerical error,
> than the initial point so that I could compute everything on the linear
> scale. This intuition is correct in the typical set, but way out in the tails
> it is not unlikely that each new point can have drastically lower energy 
> than the first point. This results in overflowed weights which overflows
> the probabilities and forces the sampler to choose the initial point over
> and over again. This results in covariances estimates to be nearly
> zero which then gives the pathological mass matrices.
> 
> This one is one me — in fact Bob had mentioned that I should be
> calculating this on the log scale in the code review. Jet lag is smacking
> me over the head right now,

I sure wish I could work at your level with jet lag bashing
me over the head.

> but I’ll switch everything to the log scale
> tomorrow morning and see if that fixes the problem, at which point 
> Sebastian can see if it fixes all of his examples.

Is the point that once it underflows, it's dead?  Otherwise,
I don't see there being much difference, because the underflowed
term wouldn't have been chosen anyway.

- Bob

**Comment by betanalpha** [comment] 2016-06-08 08:39
Superseded by #1904.

**Closed by betanalpha** 2016-06-08 08:39 UTC
Labels: Bug
