### ISSUE TITLE
Line number not reporting in some runtime errors

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#2348] opened 2017-07-05 01:36 UTC
#### Summary:
Errors in bad assignment don't have line numbers. It'd be useful if they did. It would also be consistent.

#### Description:
Line numbers should accompany all runtime errors.

#### Reproducible Steps:
Run this minimal example:

```stan
transformed data {
  real x[0] = { 1.0 };
}
parameters {
  real<lower = 0, upper = 1> theta;
}
model {
}
```

Compare output with:
```stan
parameters {
  real theta;
}
model {
  theta ~ normal(0, -1);
}
```

#### Current Output:
The current output is:
```
<some preliminary stuff>
assign: size of left-hand side (0) and size of right-hand side (1) must match in size
```

#### Expected Output:
Here's what it should look like to be consistent with the other errors:
```
<some preliminary stuff>
assign: size of left-hand side (0) and size of right-hand side (1) must match in size  (in 'test.stan' at line 2)
```

#### Additional Information:
@mitzimorris, mind helping track this down?

#### Current Version:
v2.16.0

**Comment by bob-carpenter** [comment] 2017-07-05 19:14
Duplicate of https://github.com/stan-dev/stan/issues/2280

**Closed by bob-carpenter** 2017-07-05 19:14 UTC
