### ISSUE TITLE
Algebra Solver

### ISSUE THREAD

**Issue by charlesm93** [stan-dev/stan#2300] opened 2017-05-04 21:10 UTC
#### Summary:
This related to issue #2023  and the pending pull request #2023 . Expose the algebraic function. I'm raising the issue now, because I do not expect the signature for `algebra_solver` to change. Given this is a higher-order function, I will follow the scheme used for the ODE solvers.

#### Description:
Allows users to solve systems of algebraic equations, given an initial guess.

#### Additional Information
If we move to C++11, we could change the signature, notably by removing the x_r and x_i arguments. I expect we'll however still need the parms argument to calculate the Jacobian.

#### Current Version:
v2.15.0

**Comment by charlesm93** [comment] 2017-05-09 13:44
Following the example of the ODE integrators, I got a working prototype. However, I can't get rid of the argument `std::string& solver_name`, which is equivalent to `std::string& integration_function_name`, in the constructor of the algebra_solver structure (.../lang/ast/node/algebra_solver_def.hpp). Since there is only one solver, I do not need this argument, but I get a bug if I don't include it.

It is not a error at compilation, but when I run the test, all the arguments are "misplaced" -- pushed to the left, as though an additional argument were constructed at the beginning. Which prompts several error messages from the parser.

Can I view how the parser attempts to call the function? As far as I can tell, no hpp file gets produced if the parsing fails.

**Comment by bob-carpenter** [comment] 2017-05-10 18:40
Is there a public branch where I can look at what you've done?  

The problem is that if the grammar rule doesn't fire, you won't get any output.  You can instrument the grammar rules themselves with print statements, but it's a huge pain because it requires semantic actions (it'll get easier with lambdas in C++11).  You need to make sure the parser children (right hand side of rules) and the semantic coercion that maps the sequence of terminals into the parent category match.

**Comment by charlesm93** [comment] 2017-05-10 19:00
@bob-carpenter thanks for the pointers. The branch I used is feature/issue-2300-algebra_solver.

**Comment by bob-carpenter** [comment] 2017-05-11 13:20
Did you make sure to synch the fusion adaptor declarations in `term_grammar_def.hpp`?

```
BOOST_FUSION_ADAPT_STRUCT(stan::lang::algebra_solver,
                           (std::string, solver_name_)
                           (std::string, system_function_name_)
                           (stan::lang::expression, x_)
                           (stan::lang::expression, y_)
                           (stan::lang::expression, dat_)
                           (stan::lang::expression, dat_int_) )

BOOST_FUSION_ADAPT_STRUCT(stan::lang::algebra_solver_control,
                           (std::string, solver_name_)
                           (std::string, system_function_name_)
                           (stan::lang::expression, x_)
                           (stan::lang::expression, y_)
                           (stan::lang::expression, dat_)
                           (stan::lang::expression, dat_int_)
                           (stan::lang::expression, rel_tol_)
                           (stan::lang::expression, fun_tol_)
                           (stan::lang::expression, max_num_steps_) )
```

the rule in the same file,

```
     algebra_solver_control_r
        %= (string("algebra_solver") >> no_skip[!char_("a-zA-Z0-9_")])
        >> lit('(')              // >> allows backtracking to non-control
        >> identifier_r          // 1) system function name (function only)
        >> lit(',')
```

and the AST in `lang/ast/node/algebra_solver.hpp`:

```
    struct algebra_solver {
    
      /**
       * Name of solver.
       */
       std::string solver_name_;
```

If you do, I don't see a problem with getting rid of the name.  

On the other hand, you should probably leave it in to cover the condition where we add new solvers as we did with ODE integrators.

**Comment by charlesm93** [comment] 2017-05-11 18:12
@bob-carpenter : I edited the files you pointed out (in addition to `algebra_solver_def.hpp` and `expression_visgen.hpp`), but this produces the error I mentioned in my previous post. Namely, for the following call to the function:
```
functions {
  vector algebra_system (vector x,
                         vector y,
                         real[] dat,
                         int[] dat_int) {
    vector[2] f_x;
    f_x[1] = x[1] - y[1];
    f_x[2] = x[2] - y[2];
    return f_x;
  }
}

data {
}

transformed data {
  vector[2] x;
  vector[2] y;
  real dat[0];
  int dat_int[0];
  vector[2] theta;

  theta = algebra_solver(algebra_system, x, y, dat, dat_int);
}
```

The error message is:
```
C++ exception with description "PROGRAM ERROR, MESSAGE(S) FROM PARSER:
first argument to algebra_solver must be the name of a function with signature (vector, vector, real[], int[]) : vector second argument to algebra_solver must have type vector for initial guess; found type = ill formed. fourth argument to algebra_solver must have type real[] for real data; found type = vector. fifth argument to algebra_solver must have type int[] for integer data; found type = real[]. 
" thrown in the test body.
```

My guess is the first argument (the name of the function, which would have type "ill formed") gets passed as the second argument, the second as the third, etc. So indeed the fourth argument is read in as the third argument, and is a vector instead of a real[], and the fifth argument a real[] instead of an int[]. It is as though a "rogue" first argument, which I gather corresponds to the name of the function, still got passed.

The key is to find where this rogue argument gets passed. That was why I wanted to see what the code parser actually wrote.

Note: I only made changes to the algebraic_solver (not algebraic_solver_control). The changes, which cause the bug, are on GitHub.

**Comment by bob-carpenter** [comment] 2017-05-12 21:08
The issue is probably in the test condition or signature here. The `alg_fun` must be getting passed because you're finding `alg_fun.system_function_name_` rather than failing to compile.  Are you sure the name you're getting for that is the name of a function with the right signature?  You can grab the available function signatures and print them.

You're trying to find a function that returns a `vector`, taking `(vector, vector, real[], int[])` arguments.

```
    template <class T>
    void validate_algebra_solver_non_control_args(const T& alg_fun,
                                                  const variable_map& var_map,
                                                  bool& pass,
                                                  std::ostream& error_msgs) {
      pass = true;
      expr_type sys_result_type(VECTOR_T, 0);
      std::vector<expr_type> sys_arg_types;
      sys_arg_types.push_back(expr_type(VECTOR_T, 0));  // x
      sys_arg_types.push_back(expr_type(VECTOR_T, 0));  // y
      sys_arg_types.push_back(expr_type(DOUBLE_T, 1));  // dat
      sys_arg_types.push_back(expr_type(INT_T, 1));  // dat_int
      function_signature_t system_signature(sys_result_type, sys_arg_types);
      if (!function_signatures::instance()
          .is_defined(alg_fun.system_function_name_, system_signature)) {
        error_msgs << "first argument to "
                   << "algebra_solver"
                   << " must be the name of a function with signature"
                   << " (vector, vector, real[], int[]) : vector ";
        pass = false;
      }
```

**Comment by charlesm93** [comment] 2017-06-24 15:06
> Are you sure the name you're getting for that is the name of a function with the right signature?

Yes, the function that gets passed has the right signature. However, the first element of `alg_fun` doesn't seem to be the name of that function, rather the name of the solver ("algebra_solver") -- I do not know this for sure, this is based on the "rogue argument" theory.

In term_grammar_def.hpp, what do the following blocks of code do:

(1)
```
algebra_solver_control_r
        %= (string("algebra_solver") >> no_skip[!char_("a-zA-Z0-9_")])
        > ...
```
In particular what is the `no_skip[!char_("a-zA-Z0-9_")]` for ?

(2)
```
      factor_r.name("expression");
      factor_r =
        integrate_ode_control_r(_r1)[assign_lhs_f(_val, _1)]
        | integrate_ode_r(_r1)[assign_lhs_f(_val, _1)]
        | algebra_solver_control_r(_r1)[assign_lhs_f(_val, _1)]
        | algebra_solver_r(_r1)[assign_lhs_f(_val, _1)]
        | (fun_r(_r1)[assign_lhs_f(_b, _1)]
```

Is it possible they determine the first element of alg_fun. For the ODE integrator, what determines the first element of integration_function_name?

**Comment by bob-carpenter** [comment] 2017-06-24 16:31
You probably want `lit("algebra_solver")` rather than `string("algebra_solver")`.  With the latter, the string itself gets passed as a semantic argument.  That could be leading to an extra argument.

Unpacking `no_skip[!char_("a-zA-Z0-9_")]`:

* `no_skip` prohbits whitespace before matching the argument

* `!` causes failure if the argument is matched

* `char_(...)` matches any single character specified in the argument

* `a-zA-Z0-9_` matches any character in the range `a` to `z`, `A` to `Z`, and `0` to `9`, and also matches a single underscore

Together, it stops you from finding any characters after the match;  e.g., `algebra_solverJUNK` would not allow `algebra_solver` to match.

**Comment by charlesm93** [comment] 2017-06-26 11:39
> You probably want lit("algebra_solver") rather than string("algebra_solver"). With the latter, the string itself gets passed as a semantic argument. That could be leading to an extra argument.

Yep, that was the culprit. Well, that takes care of the grammar files :) I'll write the "bad model" unit tests and submit a pull-request.

**Comment by charlesm93** [comment] 2017-06-26 14:00
In `parser_generator_test.cpp`: As far as I can tell, the test looks at the models under test-models/good/parser-generator/. For each model there, there is an accompanying .hpp file, which corresponds to the C++ translation of the stan file. Should this hpp file be supplied manually, or should the test create it?

I'm asking because just putting the .stan file didn't work, but I fail to see the point of the test if we supply the .hpp file manually.

**Comment by betanalpha** [comment] 2017-06-26 14:02
make automatically parses necessary .stan files into .hpp files
before compiling and running the tests.

See https://github.com/stan-dev/stan/blob/develop/make/tests <https://github.com/stan-dev/stan/blob/develop/make/tests>.

**Comment by bob-carpenter** [comment] 2017-06-26 15:58
I think for most of these cases, the .hpp is generated as a string by the compiler and then tested against expected output.  See the actual tests.

**Comment by charlesm93** [comment] 2017-06-26 16:51
Thank you for the explanation and the pointers. Looks like I had an error in my model, which why the .hpp file wasn't created. I opened a pull-request, but for the automatic tests to pass, we'll first need to add the algebraic solver to the math repo (pull-request #516).

**Comment by bob-carpenter** [comment] 2017-06-26 16:54
The link is to the math repo, so you need the full path, https://github.com/stan-dev/math/pull/516

**Comment by avehtari** [comment] 2017-08-13 12:32
@charlesm93 can you add to the stan-reference documentation which algorithm is used in the solver and a reference to the which library is used? Couldn't find these in the latest develop branch documentation.

**Comment by bob-carpenter** [comment] 2018-02-07 21:39
I'm closing this issue.  If I'm doing this in error @charlesm93, please re-open.

**Closed by bob-carpenter** 2018-02-07 21:39 UTC

**Comment by charlesm93** [comment] 2018-02-07 22:05
@bob-carpenter yup, all good to close.
