### ISSUE TITLE
autodiff statefulness

### ISSUE THREAD

**Issue by fredRos** [stan-dev/stan#1475] opened 2015-06-02 20:31 UTC
## Bug Report

This is in reference to the wiki entry https://github.com/stan-dev/stan/wiki/Automatic-Differentiation-API. I know it says the instructions don't apply to the `develop` branch so I found ways to make it work anyways, then I came across this when trying to simply use stan as an autodiff library in C++. The changes I needed to make were
```cpp
using stan::math::var;
using stan::math::recover_memory;
var x = 1;
recover_memory();
```
instead of
```cpp
stan::math::var x = 1;
stan::math::recover_memory()
```

__Version__
822ab42d0
__Description__
The gradient is incorrect if independent variables of type `stan::math::var` are reused. The output changes from one wrong value to another wrong value if `recover_memory` is called in between calls. Things work fine if no `var` is reused or if only the dependent `var` is reused.
__Steps__
A minimal working example that can be compiled according to the instructions at https://github.com/stan-dev/stan/wiki/Automatic-Differentiation-API#basic-usage
```cpp
#include <stan/math/prim/arr/meta.hpp>
#include <stan/math/prim/mat/meta.hpp>
#include <stan/math/prim/scal/meta.hpp>
#include <stan/math/rev/scal/meta.hpp>
#include <stan/math/prim.hpp>
#include <stan/math/rev.hpp>

#include <iostream>

using std::cout;
using std::endl;
using stan::math::var;
using stan::math::recover_memory;

template <typename T1, typename T2, typename T3, typename T4>
void print(const T1& x, const T2& mu, const T3& sigma, T4& z, const std::vector<double>& gradients, const std::string& msg="")
{
    std::cout << msg << std::endl
              << "z:       " << z.val() << std::endl
              << "x:" << x << endl
              << "mu:" << mu << endl
              << "sigma:" << sigma << endl
              << "dz / dx: " << gradients[0] << std::endl
              << "dz / dmu: " << gradients[1] << std::endl
              << "dz / dsigma: " << gradients[2] << std::endl;
}

template <typename T1, typename T2, typename T3, typename T4>
void gradient_reuse(const T1& x, const T2& mu, const T3& sigma, T4& z, bool recover=false)
{
    std::vector<var> independent_vars{x, mu, sigma};
    std::vector<double> gradients;
    z.grad(independent_vars, gradients);

    // if memory not recovered, 2nd gradient is wrong
    // if memory recovered too early, a 2nd call to the gradient sometimes leads to a segfault
    if (recover)
        recover_memory();

    print(x, mu, sigma, z, gradients, std::string("reuse with") + (recover ? "" : "out") + " recover");
}

void gradient_new(bool recover=true)
{
    var x = 1.0, mu = 0.0, sigma = 1.0;
    var z = normal_log(x, mu, sigma);

    std::vector<var> independent_vars{x, mu, sigma};
    std::vector<double> gradients;
    z.grad(independent_vars, gradients);

    // if memory not recovered, 2nd gradient is wrong
    // if memory recovered too early, a 2nd call to the gradient yields a segfault
    if (recover)
        recover_memory();

    print(x, mu, sigma, z, gradients, std::string("new with") + (recover ? "" : "out") + " recover");
}

void test_suite(bool recover)
{
    var x = 1.0, mu = 0.0, sigma = 1.0;

    // everything should work as expected
    gradient_new(recover);
    gradient_new(recover);

    // first call should give same result as above
    var z1 = normal_log(x, mu, sigma);
    gradient_reuse(x, mu, sigma, z1, recover);

    // x, mu, sigma are reused => gradient is off
    var z2 = normal_log(x, mu, sigma);
    gradient_reuse(x, mu, sigma, z2, recover);

    // reuse z2 but not x, mu, sigma => gradient OK
    var x2 = 1.0, mu2 = 0.0, sigma2 = 1.0;
    z2 = normal_log(x2, mu2, sigma2);
    gradient_reuse(x2, mu2, sigma2, z2, recover);
}

int main()
{
    // if gradient is incorrect, the values differ depending on
    // whether memory recovered between calls
    test_suite(false);
    test_suite(true);
    return 0;
}
```
__Output__
```
new without recover
z:       -1.41894
x:1
mu:0
sigma:1
dz / dx: -1
dz / dmu: 1
dz / dsigma: 0
new without recover
z:       -1.41894
x:1
mu:0
sigma:1
dz / dx: -1
dz / dmu: 1
dz / dsigma: 0
reuse without recover
z:       -1.41894
x:1
mu:0
sigma:1
dz / dx: -1
dz / dmu: 1
dz / dsigma: 0
reuse without recover
z:       -1.41894
x:1
mu:0
sigma:1
dz / dx: -3
dz / dmu: 3
dz / dsigma: 0
reuse without recover
z:       -1.41894
x:1
mu:0
sigma:1
dz / dx: -1
dz / dmu: 1
dz / dsigma: 0
new with recover
z:       -1.41894
x:1
mu:0
sigma:1
dz / dx: -1
dz / dmu: 1
dz / dsigma: 0
new with recover
z:       -1.41894
x:1
mu:0
sigma:1
dz / dx: -1
dz / dmu: 1
dz / dsigma: 0
reuse with recover
z:       -1.41894
x:1
mu:0
sigma:1
dz / dx: -1
dz / dmu: 1
dz / dsigma: 0
reuse with recover
z:       -1.41894
x:1
mu:0
sigma:1
dz / dx: -2
dz / dmu: 2
dz / dsigma: 0
reuse with recover
z:       -1.41894
x:1
mu:0
sigma:1
dz / dx: -1
dz / dmu: 1
dz / dsigma: 0
```
__Expected Output__
The expected output for a single run is
```
z:       -1.41894
x:1
mu:0
sigma:1
dz / dx: -1
dz / dmu: 1
dz / dsigma: 0
```
The two cases that don't match the expected result are the 2nd runs that the reuse the variables
```
    var z1 = normal_log(x, mu, sigma);
    gradient_reuse(x, mu, sigma, z1, recover);

    // x, mu, sigma are reused => gradient is off
    var z2 = normal_log(x, mu, sigma);
    gradient_reuse(x, mu, sigma, z2, recover);
```
Note that without `recover_memory()`, `dz / dx: -3`, while with `recover_memory()`, we have `dz / dx: -2`
__Additional Information__
In my original test that had all this in one big function, I observed segfaults if `recover_memory()` was called twice. The problem went away in this minimal working example but I guess this is just by chance.

**Comment by syclik** [comment] 2015-06-02 20:35
@fredRos, thanks for the detailed info. Just wanted to let you know that I saw it, I've assigned myself, and will look at it. (won't have time until next week -- we're trying to get a release out and work on some of the interfaces for the rest of the week)

**Comment by bob-carpenter** [comment] 2015-06-02 21:11
Thanks for the careful report --- we really appreciate code examples.  I'm going to close this issue, because while it's not an ideal design we have, it's also not a bug according to our intended usage.

If you have a reproducible example where `recover_memory()` segfaults, please open another issue with that example.  It shouldn't segfault no matter how you call it. 

As for the autodiff lib, the `var` instances aren't intended to be reused.  They're just lightweight pointers to `vari` instances. The intent is that `recover_memory()` is called after the derivatives are extracted after each use.  Any other use is going to mess up any existing variables you had because derivatives will get propagated twice.  Although not ideal, it's a consequence of the design, not a bug. 

What we're really hoping is that everyone uses our encapsulating functionals, which don't have any of these issues with using the raw autodiff.  

We have a paper that we're about to release on how the autodiff works end to end and we'll be revising the Wiki to match. The best way to see how it's intended to be used is in the deifnition of functionals like gradient() and hessian().  If you want the paper, just send me an e-mail at carp@alias-i.com and I can send you a draft.  

I don't understand why the using statements would give you different answers, so presumably that was just for convenience.

**Closed by bob-carpenter** 2015-06-02 21:11 UTC

**Comment by fredRos** [comment] 2015-06-03 10:21
Thanks for the quick reply. I will send Bob an e-mail to get the
draft. If the wiki is updated to document this rather surprising and
not very convenient behavior, then there should be no problem for
those who read the manual carefully.

I know very well how the functional approach make life easier for the
library developers. But sometimes state helps to reuse
results. Suppose I needed gradients wrt. y of a multivariate normal
N(y|mu, Sigma) and the Sigma is fixed. Then I guess you'd have to
invert, Cholesky decompose ... Sigma each time I need the
gradient. This is what I could get around if I use the autodiff
library manually.  Do you memoise these things internally? Or is it
just recomputed every time?

As for the `using` statements: sorry about the confusion. The code
compiles fine without
```cpp
using stan::math::var;
using stan::math::recover_memory;
```
and instead
```cpp
stan::math::var z =...
stan::math::recover_memory()
```

And regarding the segfault, I created a new issue #1478. It might be related
to the double use of variables.

**Comment by betanalpha** [comment] 2015-06-03 11:22
> Do you memoise these things internally?
> 

Essentially.  If the covariance matrix is filled with vars
then we’ll decompose it and push the autodiff through
the decomposition, but if it’s filled with doubles then
we’ll only invert.  And the inversion can be avoided
by using the multi_normal_cholesky distribution which
takes in the Cholesky decomposition directly.  

But you can do a similar trick inside any functor to
reuse any intermediate results while still benefiting
from the encapsulation.
