### ISSUE TITLE
Misleading / Incorrect Error Message; vector ~ Dirichlet()

### ISSUE THREAD

**Issue by davidmanheim** [stan-dev/stan#1755] opened 2016-01-19 00:44 UTC
When (accidentally/incorrectly) I had a vector instead of a simplex, it gave me the error;

stan::math::dirichlet_log: probabilities is not a valid simplex. sum(probabilities) = X, but should be 1.

This led me off a bit until I realized the actual problem.

Also, for almost all errors, including this one, it says "If this warning occurs sporadically, such as for highly constrained variable types..." - but this isn't a warning, it's an error, and it's not a misspecification, it's a type error.

If possible, I assume the best solution would be to catch this error when compiling.

**Comment by syclik** [comment] 2016-01-19 03:44
Hi David,

What do you expect the message to say? The message itself looks clear. It's
coming from the Math library. Also, the Dirichlet distribution allows for
any Stan vector to be used, not just a Stan simplex.

Regarding the sporadic message: agree -- it's already on the to-do list,
but it won't catch this.

If there isn't a concrete suggestion to change the wording or behavior,
I'll close the issue.


Daniel

**Comment by betanalpha** [comment] 2016-01-19 12:52
I think David wants the sampling to simply end given that the simplex
constraint will never be met in his model.  The problem is that these
messages do not always mean that the simplex constraint will never
be met — most often they arise when the simplex constraint is just
barely violated in which case we really do want to abort the current
sample and try again.  This is another example of the Stan modeling
language being too expensive to be able to always identify problems
exactly.

**Comment by syclik** [comment] 2016-01-19 15:33
That's also what I read the intent to be. Since there's no actual fix here, I'll close the issue.

**Closed** 2016-01-19 15:33 UTC
