### ISSUE TITLE
Segfault in optimizing for simple exponential model

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2576] opened 2018-07-09 23:27 UTC
_From @NathanWycoff on July 9, 2018 17:0_

This issue ported over from [here](http://discourse.mc-stan.org/t/segfault-in-simple-exponential-model/4776).

Hello everyone,

I want to first thank the developers for an awesome software package that has helped me extensively in several projects.

This bug doesn't really affect me, but I felt like I should report it anyways. With a specific model/data combination and a specific random seed, I observe a segfault when invoking the optimizing function. The model is rather simple.

Steps to reproduce:
1) Please find the model attached [exp_model.txt](https://github.com/stan-dev/rstan/files/2177192/exp_model.txt)
2) Please find an R script attached [breaks_stan.txt](https://github.com/stan-dev/rstan/files/2177185/breaks_stan.txt). Rename these if necessary (not sure why github won't accept R/stan files).
3) Modify line 36 of the R file to point to where exp_model.stan lives on disk.
4) Run the R file in its entirety. This is important to advance PRNG to the point of failure. This involves sampling from the posterior, but it terminates in less than half a second on my machine. 

Bug Description:
Posterior sampling from the model works fine. Afterwards, when trying to find the optimum, it will print the initial loglikelihood, then R will freeze for about half a minute before this message appears (the shrug emoji is just my replacement for the standard prompt):

```

    ¯\_(ツ)_/¯ optimizing(mod, data = stan_dat)
    Initial log joint probability = -8.18984

     *** caught segfault ***
    address 0x256b38fff, cause 'memory not mapped'

    Traceback:
     1: .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: 0x7fdbf945fd70>,     dll = list(name = "Rcpp", path = "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/libs/Rcpp.so",         dynamicLookup = TRUE, handle = <pointer: 0x7fdbf9708d90>,         info = <pointer: 0x7fdbf986aa20>), numParameters = -1L),     <pointer: 0x7fdbf97fb9b0>, <pointer: 0x7fdbf9739640>, .pointer,     ...)
     2: sampler$call_sampler(c(args, dotlist))
     3: .local(object, ...)
     4: optimizing(mod, data = stan_dat)
     5: optimizing(mod, data = stan_dat)

    Possible actions:
    1: abort (with core dump, if enabled)
    2: normal R exit
    3: exit R without saving workspace
    4: exit R saving workspace
```

This only seems to occur for a specific PRNG state.

Facts about the platform this was discovered on:

OS: Mac OS High Sierra 10.13.2

R: R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

rstan (Version 2.17.3, GitRev: 2e1f913d3ca3)

R was executed directly from a bash terminal.

_Copied from original issue: stan-dev/rstan#545_

**Comment by bob-carpenter** [comment] 2018-07-09 23:29
Thanks for reporting.  This one should be easy to track down.

**Comment by sakrejda** [comment] 2018-07-10 02:30
Oh no, there are gammas!

**Comment by bob-carpenter** [comment] 2018-07-10 06:08
gammas (and inverse gammas and lognormals) can be useful for avoiding zero when optimizing

**Comment by sakrejda** [comment] 2018-07-15 20:08
Yes but some of the gamma-related functions caused problems in the past since they're calculated as power series.  I was hoping we were done with that.  NOt sure exactly what the issue is here.

**Comment by bob-carpenter** [comment] 2018-07-16 12:33
Here's the model and program so people don't have to click through:

```
data {
    // Hyperparams
    real<lower=0> alpha_l1_0;
    real<lower=0> alpha_l2_0;
    real<lower=0> beta_l1_0;
    real<lower=0> beta_l2_0;

    //Observation
    real<lower=0> t1;
    real<lower=0> t2;
}
parameters {
    real<lower=0> lambda_1;
    real<lower=0> lambda_2;
}
transformed parameters {
    real nu;
    nu = lambda_1 / 2 + lambda_2;
}
model {
    // -- Prior --
    lambda_1 ~ gamma(alpha_l1_0, beta_l1_0);
    lambda_2 ~ gamma(alpha_l2_0, beta_l2_0);

    // -- Likelihood -- 
    t1 ~ exponential(lambda_1);
    t2 ~ exponential(nu);
}
```

and the R script

```
#!/usr/bin/Rscript
#  breaks_stan.R Author "Nathan Wycoff <nathanbrwycoff@gmail.com>" Date 07.05.2018

## Estimating paramters of an exponential
require(rstan)
set.seed(123)

# True params
lambda_1 <- 3
lambda_2 <- 2

# Priors for bayesian inference
# nu is defined as lambda_1 / 2 + lambda_2
alpha_l_0 <- 1
alpha_n_0 <- 1
beta_l_0 <- 1
beta_n_0 <- 1

# sim params
bayes_iters <- 100

# Observe data
T1 <- rexp(1, lambda_1)
T2 <- rexp(1, lambda_1 / 2 + lambda_2)

### Estimation via bayes + MC
stan_dat <- list(
                 alpha_l1_0 = 0.2,
                 alpha_l2_0 = 0.2,
                 beta_l1_0 = 1,
                 beta_l2_0 = 1,
                 t1 = T1,
                 t2 = T2)

iters <- 5e3
path <-  'stan/exp_model.stan'
fit <- stan(file = path, data = stan_dat,
            iter = iters, chains = 2, control = list(adapt_delta = 0.99))

mod <- stan_model(path)
optimizing(mod, data = stan_dat)
```

**Comment by bob-carpenter** [comment] 2018-07-16 12:33
In this case, the parameters are data, so I don't think it's `lgamma` and `digamma` causing problems.

**Comment by bob-carpenter** [comment] 2018-07-16 12:34
I'm also confused why there's a `sampler$call_sampler` on the stack trace when we're doing optimization.

**Comment by rok-cesnovar** [comment] 2020-05-09 13:29
not segfaulting on develop. closing.

**Closed by rok-cesnovar** 2020-05-09 13:29 UTC
Labels: algorithm, bug
