### ISSUE TITLE
Setting lower bounds and mutliplier at the same time

### ISSUE THREAD

**Issue by mhollanders** [stan-dev/stan#3293] opened 2024-06-18 05:50 UTC
Hello,

I'm gathering that the following is not possible:

```
parameters {
  real<lower=0, multiplier=2> sigma;
}
```

I think such a construction is useful if the parameter is not always included but if it is, it needs both constraints, for instance:

```
parameters {
   row_vector<lower=(x ? [0, 0, 0] : [ ]), multiplier=(x ? [2, 2, 2] : [ ])>[x ? 3 : 0] sigma;
}
```

Is there a way to do this?

Thanks!

**Comment by bob-carpenter** [comment] 2024-06-18 08:44
Not yet.  It's something we've been thinking about.  The main problem is that transforms are ordered and their composition doesn't always make sense.  When you write `<lower=0, multiplier=2>`, then I presume your intent is to have the constraining transform first apply the multiplier, then the lower bound, so that the map f:(-inf, inf) -> (0, inf) is f(x) = exp(2 * x).  It's also possible to do it the other way around, f(x) = 2 * exp(x). To disambiguate, we'd need to have something like 

```stan
real<lower=0><multiplier=2> sigma1;  // sigma1 = exp(sigma1_unconstrained) * 2
real<multiplier=2><lower=0> sigma2;  // sigma2 = exp(2 * sigma2_unconstrained)
```

to clarify which of these transforms is desired.  We're worried that people will confuse the ordering of composition, which here I've assumed is left to right, or equivalently, inside out from `real`.  

Now consider offsets, where we might have `<lower=0, offset=2>`.  IN this case, the ambiguity is between the constraining transforms f(x) = 2 + exp(x) and f(x) = exp(2 + x).  The problem is that the former maps (-inf, inf) to (2, inf), whereas the latter maps (-inf, inf) to (0, inf).

We'd like to be able to extend these transforms to things with upper and lower bounds, orderings, simplexes, etc.

Having said all that, if you want the effect you are after, you can code it yourself as the Jacobian is trivial here for f(x) = exp(2 * x), where f'(x) = 2 * exp(2 * x).  Wolfram Alpha is very convenient for scalar functions, where you can just enter `d/dx exp(2 * x)` and it'll give you the answer.

```stan
parameters {
  real sigma_unc;
}
transformed parameters {
  real<lower=0> sigma = exp(2 * sigma_unc);
}
model {
  target +=  2 * exp(2 * sigma_unc);  // more efficiently, target += 2 * sigma;
}
```

You can do the same exercise if you intended the other way around, 2 * exp(sigma_unc).

I'm going to close this issue as we already have similar issues in the math library (e.g., https://github.com/stan-dev/math/issues/2959), which is where we'd start.  We're actively working on this and want a general solution, perhaps with user-defined transforms, but as with all things Stan, there's no schedule for when it'll be done.

**Closed as completed by bob-carpenter** 2024-06-18 08:44 UTC
