### ISSUE TITLE
Enable valued-instantiations in transformed data.

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#1453] opened 2015-05-19 12:46 UTC
I just want to be able to do
  
    transformed data {
      int<lower=1> N <- 20;
      real y[N];
      ...
    }

instead of having to a hard-coded literal for the instantiated dim every time.

**Comment by syclik** [comment] 2015-05-19 16:31
duplicate of #1145

**Closed by syclik** 2015-05-19 16:31 UTC
