### ISSUE TITLE
control CSV writer output precision

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2245] opened 2017-03-12 17:08 UTC
#### Summary:

Right now, CmdStan defaults to 6 places of precision and writes out in ASCII.  Allow the number of decimal places of precision to be controlled through the services directly in Stan.

#### Current Version:
v2.14.0

**Comment by martinmodrak** [comment] 2018-06-04 08:54
Duplicate of #2515

**Closed by martinmodrak** 2018-06-04 08:54 UTC
Labels: feature, interface
