### ISSUE TITLE
Repeated Calls of stan

### ISSUE THREAD

**Issue by GGMeyers** [stan-dev/stan#1654] opened 2015-10-29 14:54 UTC
I just upgraded to rstan v 2.8 from v 2.6.  An analysis that I am doing calls stan in a loop.  For a low number of calls, everything works.  For a higher number of calls, errors happen.  These errors did not happen when I was using 2.6.  If the fix is not quick, I would like instructions on how to reinstall v 2.6.

**Comment by bob-carpenter** [comment] 2015-10-29 17:25
Thanks for filing an issue.  I'm moving it to the RStan repo's issue tracker.  See:

https://github.com/stan-dev/rstan/issues/225

To answer your question about 2.6, you can retrieve the full source from prior versions under Releases in the RStan repo:

https://github.com/stan-dev/rstan/releases

**Closed by bob-carpenter** 2015-10-29 17:25 UTC

**Comment by GGMeyers** [comment] 2015-10-29 19:47
Hi Bob. Thanks for looking into this.  One other related problem.  When I upgraded to 2.8 I also upgraded my R to 3.2 from 3.0.something.  When I try to reinstall stan 2.6 it won't install with R 3.2.  I have been able to move down to 3.1 - same result.  But I can't find an installer for a 3.0 version of R.

The reason I upgraded is that I wanted to use the loo package, which requires R 3.1.

Do you have any short-term suggestions? I can forgo going to the loo for awhile, but I would like to run my current R/stan scripts.

**Comment by bob-carpenter** [comment] 2015-10-29 19:59
Please see the question below.

I don't know the answer and issues are the wrong place
for a Q&A on workarounds for old versions of RStan.

I'm moving this discussion to our mailing list.  Issues
are not the place to have this discussion.  I bcc-ed
the OP, GGMeyers.  Oops, can't do that because our damn
issue tracker replaces the OP's address with a reply-to-list
tag (an option that the open source project management book
I'm reading strongly recommends against due to the risk of
thinking you're replying to the sender by hitting reply-to-sender
and your mail goes to the whole list by default because of
the reply-to fiddling done on the list).

I think it's very bad news when our users want to revert to
older versions of our software, either because we intentionally
or unintentionally broke things.  I'd rather release new features
more slowly if that's what it takes to get more tests in.

I've already created the R issue:

https://github.com/stan-dev/rstan/issues/225

I forgot to add that we need a unit test that fails in RStan 2.8
and will succeed under the patch.  It's the only way to prevent
regression bugs (regressing to past poor behavior, not the statistical
kind of regression).

- Bob
