### ISSUE TITLE
exposing to_matrix functions to language

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1956] opened 2016-07-14 14:41 UTC
#### Summary:

@ziyuang brought this up in <a href="https://github.com/stan-dev/stan/pull/602#issuecomment-232636221">an issue comment</a>:

... the functions discussed here (`matrix to_matrix(vector, int, int)`, `matrix to_matrix(row_vector, int, int)`, and `matrix to_matrix(real[], int, int)`), which seem already added to Stan, are not available, and cannot be found in the documentation.
#### Description:

See above.  We just want to expose these functions if they exist in the language.
#### Current Version:

v2.10.0

**Comment by randommm** [comment] 2016-08-18 21:13
Does this really exists? Where? I don't remember having them implemented, nor what they do, what I know is `matrix to_matrix(vector)`, `to_matrix(row_vector)` and `matrix to_matrix(real[])` which are implemented and exposed.

**Comment by bob-carpenter** [comment] 2016-11-24 01:01
These functions do *not* exist in the stan-dev/math library (yet).

**Comment by syclik** [comment] 2016-12-24 03:33
Duplicate of #1452

**Closed by syclik** 2016-12-24 03:33 UTC
Labels: Feature, language
