### ISSUE TITLE
assertion in read_corr_L with 1 by 1 matrix

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/stan#2742] opened 2019-03-20 10:47 UTC
#### Summary:
Please provide a short couple sentence summary.

Segfault when using multilevel regression model from manual. Does `quad_form_diag` require at least 2 x 2?

#### Description:

cmdstan core dumps with message:

```
mr: stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/DenseCoeffsBase.h:425: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index) [with Derived = Eigen::Array<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
```

From earlier experiments with Python:

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffd59e1cba in stan::math::read_corr_L<double> (CPCs=..., K=K@entry=1)
    at ~/.virtualenvs/py3/lib/python3.6/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat/fun/read_corr_L.hpp:59
59        L(K - 1, K - 1) = sqrt(acc(K - 2));
```

#### Reproducible Steps:

MR example from manual:
```
data {
  int<lower=0> N;              // num individuals
  int<lower=1> K;              // num ind predictors
  int<lower=1> J;              // num groups
  int<lower=1> L;              // num group predictors
  int<lower=1,upper=J> jj[N];  // group for individual
  matrix[N, K] x;              // individual predictors
  row_vector[L] u[J];          // group predictors
  vector[N] y;                 // outcomes
}
parameters {
  corr_matrix[K] Omega;        // prior correlation
  vector<lower=0>[K] tau;      // prior scale
  matrix[L, K] gamma;          // group coeffs
  vector[K] beta[J];           // indiv coeffs by group
  real<lower=0> sigma;         // prediction error scale
}
model {
  tau ~ cauchy(0, 2.5);
  Omega ~ lkj_corr(2);
  to_vector(gamma) ~ normal(0, 5);
  {
    row_vector[K] u_gamma[J];
    for (j in 1:J)
      u_gamma[j] = u[j] * gamma;
    beta ~ multi_normal(u_gamma, quad_form_diag(Omega, tau));
  }
  for (n in 1:N)
    y[n] ~ normal(x[n] * beta[jj[n]], sigma);
}
```

data.json
```
{
"N": 3,
"y": [0,1,-1],
"K": 1,
"J": 2,
"L": 2,
"jj":[1,1,2],
"x": [[1],[1],[1]],
"u": [[1, 1], [1, 1]]
}
```

#### Current Output:

Assertion error

#### Expected Output:

Samples

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.19.0

**Comment by mcol** [comment] 2020-01-19 22:24
The problem is not with `quad_form_diag`, as this example is enough to trigger the assertion:
```
parameters {
  corr_matrix[1] Omega;
  real x;
}
model {
  x ~ std_normal();
}
```

There's this comment in `test/unit/math/prim/fun/corr_matrix_transform_test.cpp`:
```
// tests K=2 boundary case, which has a different implementation
```
But I couldn't find any check about the minimum size, nor prim tests about that. I think this is a flat-out bug in `read_corr_L`, that should return early if the correlation matrix has size 1.

**Comment by bob-carpenter** [comment] 2020-01-20 18:50
There's a PR to fix this in the math lib, so I'm going to close this issue:

https://github.com/stan-dev/math/pull/1630

**Closed by bob-carpenter** 2020-01-20 18:50 UTC
