### ISSUE TITLE
integrate_ode_bdf is causing r to crash

### ISSUE THREAD

**Issue by pkpddude1** [stan-dev/stan#2760] opened 2019-05-20 16:39 UTC
I can run this example problem below with integrate_ode_rk45 but it crashes when I try integrate_ode_bdf.  Model code included 

```
library(deSolve)
library(rstan)
library(bayesplot)
rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores())

pendulumDE = function(t, x, parms) {
  with(as.list(c(x, parms)), {
    dx1 = x2
    dx2 = -g * sin(x1)
    list(c(dx1, dx2))
  })
}
times = seq(0, 6, length=100)
start = c(x1 = 1, x2 = 0)
parms = c(g = 9.81)
out = lsoda(start, times, pendulumDE, parms)

outNoise = out
outNoise[,2] <- outNoise[,2] + rnorm(dim(out)[1], 0, 0.1)
outNoise[,3] <- outNoise[,2] + rnorm(dim(out)[1], 0, 0.1)

Test <- '

functions {
  real[] pendulum(real t,
                     real[] y,
                     real[] parms,
                     real[] x_r,
                     int[] x_t) {
    real dydt[2];
    dydt[1] = y[2];
    dydt[2] = - parms[1] * sin(y[1]);
    return dydt ;
  }
}

data {
   int<lower=1> T;
   real y[T,2] ; //observed state at time = 0
   real t0 ;
   real ts[T];
}

transformed data {
   real x_r[0]  ;
   int x_i[0] ;
}

parameters {
   real y0[2] ;
   real parms[1] ;
   vector<lower=0>[2] sigma ;
}

transformed parameters {
   real y_hat[T,2];
   y_hat = integrate_ode_rk45(pendulum, y0, t0, ts, parms, x_r, x_i);
}

model {
  parms ~ normal(8,2);
  y0 ~ normal(0,1);
  sigma ~ cauchy(0,2.5);
  for (t in 1:T) {
    y[t] ~ normal(y_hat[t], sigma);  // both y1 and y2 together in the same vector
  }
}


generated quantities {
  real simulatedX[T, 2];
  simulatedX = integrate_ode_rk45(pendulum, y0, t0, ts, parms, x_r, x_i);
}
'

nSamples = length(times)-1
t0 = times[1]
m0 = out[1,2:3]
zStan = outNoise[-1,2:3]
 

dat <- list(T = nSamples, y=zStan, t0 = t0, ts = times[-1])

res1 <- stan(model_code = Test, data = dat, chains=4, warmup=1000, iter=2000, 
             control=list(adapt_delta=0.99, max_treedepth=15), cores=4)
```

#### Current Version:
rstan v2.18.2

**Comment by bob-carpenter** [comment] 2019-05-22 15:23
Could someone check to see if this crashes in CmdStan?  It looks like it's failing during an R serialization/unserialization.

**Comment by wds15** [comment] 2019-05-22 16:29
This problem may be inexistent by now with 2.19.1. In that version we bumped the sundials version which I think solved a few memory related issues with these solvers. It's a bit unfortunate that RStan 2.19 appears to be very hard to get on CRAN.

So testing with the latest cmdstan is a way to confirm this (ideally this confirms my suspicion that the problem is solved).

**Comment by rok-cesnovar** [comment] 2020-05-09 13:02
Works on develop cmdstan. Closing.

**Closed by rok-cesnovar** 2020-05-09 13:02 UTC
