### ISSUE TITLE
rng parser error when used with compound declare-define and local variable

### ISSUE THREAD

**Issue by jgabry** [stan-dev/stan#2207] opened 2017-01-16 02:47 UTC
#### Summary:

In `generated quantities` this parses: 

```stan
int w = poisson_rng(lambda);
if (w > 1) {
  int z;
  z = poisson_rng(lambda);
  w = w + z;
}
```

but this throws a parser error (error message below in **Current Output** section): 

```stan
int w = poisson_rng(lambda);
if (w > 1) {
  int z = poisson_rng(lambda);
  w = w + z;
}
```

#### Reproducible Steps:

This works as expected: 
```r
library("rstan")
prog <- "
parameters {
  real<lower=0> lambda;
}
model {
  lambda ~ exponential(1);
}
generated quantities {
  int w = poisson_rng(lambda);
  if (w > 1) {
    int z;
    z = poisson_rng(lambda);
    w = w + z;
  }
}
"
fit <- stan(model_code = prog)
```

however changing it to `int z = poisson_rng(lambda);` causes a parser error: 
```r
prog2 <- "
parameters {
  real<lower=0> lambda;
}
model {
  lambda ~ exponential(1);
}
generated quantities {
  int w = poisson_rng(lambda);
  if (w > 1) {
   int z = poisson_rng(lambda);
   w = w + z;
  }
}
"
fit2 <- stan(model_code = prog2)
```

#### Current Output:
The first model runs and gives the output from sampling. The second errors with 

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

ERROR: random number generators only allowed in transformed data block, generated quantities 
block or user-defined functions with names ending in _rng; found function=poisson_rng in 
block=local

ERROR at line 11

  9:      int w = poisson_rng(lambda);
 10:      if (w > 1) {
 11:       int z = poisson_rng(lambda);
                                      ^
 12:       w = w + z;
```

#### Expected Output:

No parser error or, if this is intentional behavior, a clearer error message. From the current error message it's not clear why `prog2` should result in an error when `prog` doesn't. 

#### Current Version:
`v2.14.0`

**Comment by bgoodri** [comment] 2017-01-16 02:58
This seems to be a duplicate of https://github.com/stan-dev/stan/issues/2145

**Closed by bgoodri** 2017-01-16 02:58 UTC

**Comment by jgabry** [comment] 2017-01-16 03:00
Yeah looks like the same issue.
