### ISSUE TITLE
print statements don't seem to execute when initialization is bad

### ISSUE THREAD

**Issue by davharris** [stan-dev/stan#1973] opened 2016-07-25 18:13 UTC
#### Summary:

When my Stan code and/or inputs from rstan are incorrect, I usually debug-by-print if I can't spot the problem immediately.  In the simplified script below, I have a divide-by-zero error in my function of theta, and I'd like to use print statements to find the problem.  However, my print statement seems to be ignored.

Sorry if this belongs in the rstan repository. I can't tell if Stan is not emitting the print statements or if they just aren't making it through rstan. I've included my R information below.

#### Reproducible Steps:

```
library(rstan)

mc <- '
parameters {real theta;}
transformed parameters{
  real f_theta;
  f_theta = theta / 0.0;
}
model {
  print("f_theta = ", f_theta);
  target += f_theta;
}
'
sm <- stan_model(model_code = mc)
post <- sampling(sm, verbose = TRUE)
```

#### Current Output:
100 replicates of the following are printed to the screen

```
Rejecting initial value:
  Log probability evaluates to log(0), i.e. negative infinity.
  Stan can't start sampling from this initial value.
```

(and the value of `f_theta` is not visible)

#### Expected Output:

I'd like to have the contents of my print statement show up too (at least once).

#### RStan Version:
2.10.1

#### R Version:

R version 3.3.1 (2016-06-21)

#### Operating System:
OS X 10.11.6

**Comment by bob-carpenter** [comment] 2016-07-25 19:35
Thanks for reporting. We appreciate it.  This is the right repo going forward.  I'm closing, though, because although it looks like a different issue, the root cause is the same as issue #1789

**Comment by bob-carpenter** [comment] 2016-07-25 19:36
Duplicate of #1789

**Closed by bob-carpenter** 2016-07-25 19:36 UTC
