### ISSUE TITLE
Syntax error when using row_vector /= real operators

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2513] opened 2018-04-08 14:28 UTC
_From @Craig44 on April 8, 2018 4:26_

#### Summary:
Get an error in RStan for operator syntax (/= and *= )that the manual suggest I should be able to use

#### Description:
When I use stanc(STANMODEL); I get the following error
    99: 	expected_values[t,] /= rowsum;
                                          ^
PARSER EXPECTED: <expression>

I have attached the an stripped down version of the model for reproducible purposes

#### Reproducible Steps:
I have attached the STAN model, I run the following R code to demonstrate the error

`library(rstan)`
`setwd("")`
`stanc("simple.stan)`

#### Current Output:
   SYNTAX ERROR
    99: 	expected_values[t,] /= rowsum;
                                          ^
PARSER EXPECTED: <expression>

#### Expected Output:
no error

#### RStan Version:
rstan_2.17.3       StanHeaders_2.17.2

#### R Version:
R version 3.4.4 (2018-03-15)

#### Operating System:
Windows 10

[simplemodel.zip](https://github.com/stan-dev/rstan/files/1887037/simplemodel.zip)

_Copied from original issue: stan-dev/rstan#513_

**Comment by bob-carpenter** [comment] 2018-04-08 14:28
I verified there's an issue with sliced lvalues and compound declare-define.   Here's a minimal example:

```
transformed data {
  matrix[2, 3] a;
  a[1, ] /= 5;
}
```
which produces error:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

  error in 'modelf45422b23f_simple' at line 3, column 11
  -------------------------------------------------
     1: transformed data {
     2:   matrix[2, 3] a;
     3:   a[1, ] /= 5;
                  ^
     4: }
  -------------------------------------------------

PARSER EXPECTED: <expression>
```

**Comment by bob-carpenter** [comment] 2018-04-14 00:49
Sorry, my bad---it's compound arithmetic-define.

**Comment by mitzimorris** [comment] 2018-04-16 23:02
same as #2482

**Comment by mitzimorris** [comment] 2018-06-05 03:12
duplicate of #2482

**Closed by mitzimorris** 2018-06-05 03:12 UTC
Labels: bug, language
