### ISSUE TITLE
Generated C++ code does not compile when using real literals

### ISSUE THREAD

**Issue by pvdbrand** [stan-dev/stan#1690] opened 2015-11-16 12:56 UTC
When I use real (floating point) literals in my Stan model, then the generated C++ code does not compile on my machine. The cause is that my LC_NUMERIC environment variable is set to nl_NL.UTF-8, which makes boost::lexical_cast output floating point numbers with a comma as a decimal separator.

Example: 
w[1] <- 1.23;

Should compile to:
stan::math::assign(get_base1_lhs(w,1,"w",1), 1.23);

But instead it compiles to (note the decimal separator!):
stan::math::assign(get_base1_lhs(w,1,"w",1), 1,23.0);

The offending boost::lexical_cast call is in lang/generator.hpp in expression_visgen::operator()(const double_literal& x).

**Comment by syclik** [comment] 2015-11-16 13:33
Thanks for reporting the bug.

What is your LC_NUMERIC environment variable set to? I'll try to replicate that behavior on my machine.

**Comment by pvdbrand** [comment] 2015-11-16 13:40
My LC_NUMERIC environment variable is set to nl_NL.UTF-8. 

I use Xubuntu. To change the locale I go to Settings -> Language Support -> Regional Formats, then I choose "Nederland" under "Display number, dates, ...". You may need to install another language (Dutch in my case) first. You need to reboot to make the settings take effect. Other flavors of Linux will work similarly I guess.

You can check your current settings by running the command "locale" in a terminal.

Btw, I just changed the settings to en_US.UTF-8 and the model compiles fine.

**Comment by syclik** [comment] 2015-11-16 15:27
Thanks. Sorry about that -- I didn't realize you had provided the
LC_NUMERIC variable. I'll try to see if we can disable that through Boost
somehow.

**Comment by syclik** [comment] 2015-11-17 23:22
@mitzimorris, do you know how to deal with converting strings to numbers? We're having some interactions with the LC_NUMERIC environment variable.

**Comment by mitzimorris** [comment] 2015-11-18 12:51
I will change the generator code.  as noted, the boost::lexical_cast call is the culprit.

I've found several discussions of the problem and proposed workarounds.  Will investigate which is appropriate for the stan compiler.

**Comment by syclik** [comment] 2015-11-18 14:59
Thanks! I found some of those discussions and they were way over my head.

**Comment by rok-cesnovar** [comment] 2020-02-24 13:51
I tried this one with stanc3 and was unable to reproduce so I am closing.

**Closed by rok-cesnovar** 2020-02-24 13:51 UTC
Labels: bug
