### ISSUE TITLE
Numeric overflow, tgamma

### ISSUE THREAD

**Issue by ptn24** [stan-dev/stan#2255] opened 2017-03-22 17:31 UTC
#### Description:
I get the following

```
('INFO: Initial parameters', {'mu': 0.5, 'phi': 1, 'w_0': 0.69091931142090446, 'w': array([-0.27052855,  0.44121676, -0.23313663,  0.88146095,  0.1719369 ,
       -0.13115881, -0.0343557 , -0.65111515,  0.6491713 ,  0.53574831,
        0.34756648, -0.5797055 , -0.1997476 ,  0.1625951 , -0.1215    ,
        0.13889288, -0.2295226 , -0.70625209,  0.15884236,  0.39814814,
       -0.20826035,  0.29179666,  0.07323041, -0.28598118,  0.35788681,
       -0.45399123, -0.20960651,  0.06401133, -0.2308089 ,  0.24958945,
        0.90866274,  0.56040227,  0.52527381, -0.31835018,  0.54224039,
       -0.05974072, -0.09734139,  0.28207122,  0.7408952 , -0.02405463,
       -0.13910324,  0.10505472,  0.57475112, -0.40856197, -0.65439175,
        0.38553316, -0.35704467, -0.3536128 , -0.21973083, -0.20005977,
       -0.98622562,  0.0452479 ,  0.56066616,  0.55866922, -0.54499827,
        0.29682395,  0.00178766, -0.25977359,  0.19859709,  0.11461594,
        0.43245803,  0.09540582, -0.39263792, -0.10752373, -0.18090921,
       -0.66931966,  0.53382177, -0.25027437,  0.05350934, -0.72707792,
       -0.25122851,  0.20410126, -0.49383767,  0.04720082,  0.14122235,
        1.02608929, -0.15801633, -0.36897585,  0.30015339,  0.32536003,
        0.36998763, -0.25971182,  0.65974291, -0.46843143,  0.49561352,
       -0.04076968, -0.47561484, -0.45428351, -0.28851053, -0.09470851,
       -0.05752959, -0.71429534, -0.05248937, -0.53718625, -0.08136444,
        0.29121389, -0.52904384,  1.17270693,  0.5830163 ,  0.10500311,
       -0.33543509,  0.33968624,  0.39203134,  0.34695858,  0.18946337,
        0.40447077,  0.06844752,  0.75407845,  0.67607977, -0.4774629 ,
       -1.49187844, -1.09431834,  0.19460568,  0.10358412,  0.56036278,
       -0.35100866,  0.43019496, -0.30483862, -0.1053986 , -0.10937985,
       -0.1757629 , -0.52089926,  0.07407917, -0.0123624 ,  0.65450229,
       -0.21042264, -0.1554392 , -0.08431448,  0.17324623, -0.30444665,
        0.49694841, -0.68790722, -0.04641018,  0.55836847, -0.02020365,
        0.37294724,  0.02230654, -0.54061294,  0.13946673,  0.05383285,
        0.14503098,  0.28910242, -0.02209033,  0.15482229,  0.17341048,
       -0.12097925, -0.10156593, -0.88715638,  0.56543924, -0.32493027,
       -0.50438666, -0.45319082, -0.19225265,  0.12725021, -0.22586099,
        0.50104368,  0.27847687, -0.6449265 ,  0.43306655, -0.15190904,
       -0.79205534,  0.54980264,  0.35648734, -0.26078631,  0.70630172,
       -0.13703878, -0.78776348, -0.51106589, -1.07989062, -0.01767688,
        0.33610433,  0.30478381, -0.56005384,  0.72874208,  0.51151234,
       -0.22587442,  0.78917607, -0.61349265,  0.61782415,  0.11982305,
        0.6886022 , -0.1160628 , -0.13232534, -0.35537053,  0.63218095,
       -0.75187122,  0.37333861, -0.16442908, -0.23032689,  0.30354159,
        0.64103289, -0.71608173,  0.40087834,  0.28212035, -0.17129152,
        0.30147572, -0.43807175,  0.15008304,  1.02975868,  0.05971786,
        0.15891724,  0.72823555,  0.04174271, -0.09252343, -0.24688664,
       -0.24991356,  0.03926981,  0.40278358,  0.13980294,  0.15514416,
       -0.27996778,  0.05526526,  0.31514271, -0.01949379, -0.35298036,
       -0.25511445, -0.01539271, -0.04945689,  0.41982199, -0.68251022,
       -0.94827009, -0.03146817,  0.8139154 ,  0.07216416, -0.07586817,
        0.03648963,  1.03343417, -0.30914476,  0.10646841,  0.31749203,
       -0.55588963,  0.03881907,  0.26067885, -0.22743521, -0.11721607,
        0.07830396, -0.78188448,  0.37067349, -0.08065934, -0.05332349,
        0.485692  ,  0.44556641,  0.07613795, -0.45101174,  0.19181284,
       -0.5259726 , -0.11571175,  0.19393979,  0.34773642, -0.545569  ,
        0.46013049, -0.28266539, -0.26642973, -0.06214111,  0.26331269,
        0.64233009,  0.5948235 ,  0.58778781,  0.59356037, -0.50910321,
       -0.69088256, -0.32494297, -0.09768687,  0.50802146, -0.51165875,
        0.00901285,  0.9563969 ,  0.4675932 ])})
('INFO: Sampling with the following args:', {'n_jobs': 1, 'verbose': True, 'data': {'a': array([ 0.01062083,  0.00920438,  0.03228518,  0.04036716,  0.04710877,
        0.04327951,  0.04420888,  0.04589653,  0.02244839,  0.02770248,
        0.04279143,  0.05514997,  0.0395808 ,  0.00491052,  0.01032116,
        0.01297705,  0.01274098,  0.01041489,  0.00912119,  0.00825915,
        0.00911522,  0.01123634,  0.01547942,  0.01905974,  0.02077057,
        0.01655726,  0.01310074,  0.00595009,  0.00595009,  0.00638325,
        0.00614286,  0.00856103,  0.00981466,  0.00981466,  0.00613726,
        0.00746883,  0.00748989,  0.008687  ,  0.00830566,  0.00830566,
        0.00856036,  0.00369409,  0.00369409,  0.00370845,  0.00963354,
        0.01168769,  0.0105434 ,  0.00369409,  0.00414645,  0.00364338,
        0.00364338,  0.01384243,  0.01057491,  0.00680886,  0.00484254,
        0.00322747,  0.00360405,  0.00322747,  0.00387516,  0.00387516,
        0.00387516,  0.00387516,  0.00387516,  0.00387516,  0.00387516,
        0.00360405,  0.00364871,  0.00364871,  0.00364871,  0.00322747,
        0.00322747,  0.00438916,  0.00507643,  0.00412569,  0.00384472,
        0.00707275,  0.00707275,  0.00867561,  0.00845956,  0.00479252,
        0.0040456 ,  0.0040456 ,  0.00512863,  0.00510809,  0.00685027,
        0.00685027,  0.01115808,  0.01278088,  0.01656005,  0.01803778,
        0.02076805,  0.01825713,  0.01133701,  0.0103723 ,  0.01185065,
        0.00718363,  0.00713854,  0.00591808,  0.00388626,  0.00388626,
        0.00322747,  0.00709227,  0.00657202,  0.00715113,  0.00347538,
        0.00347538,  0.00397478,  0.00479568,  0.00479568,  0.00472923,
        0.00416253,  0.00384472,  0.00471685,  0.00501122,  0.00360405,
        0.00322747,  0.00529908,  0.00470202,  0.00534262,  0.00534262,
        0.00987709,  0.00748526,  0.00695678,  0.00583097,  0.00583097,
        0.00638325,  0.00581668,  0.00506592,  0.00514003,  0.01581695,
        0.01165081,  0.01165081,  0.00785325,  0.00785325,  0.00662826,
        0.00582123,  0.00725653,  0.00760497,  0.00760497,  0.01220468,
        0.01220468,  0.01488045,  0.01436035,  0.01211891,  0.00472923,
        0.00799616,  0.00659534,  0.00697323,  0.00697323,  0.00759591,
        0.00756935,  0.00659534,  0.00415095,  0.00456318,  0.00456318,
        0.00415095,  0.00503671,  0.00415095,  0.00467479,  0.00494517,
        0.00494517,  0.00494517,  0.00494517,  0.00494517,  0.00494517,
        0.0050822 ,  0.00556835,  0.00668076,  0.0137375 ,  0.01389175,
        0.01389175,  0.01418248,  0.01433393,  0.01296223,  0.03146598,
        0.03936312,  0.03727928,  0.03727928,  0.00982069,  0.01195713,
        0.01746341,  0.01501806,  0.01420386,  0.01393421,  0.01393421,
        0.00922547,  0.00618316,  0.00831198,  0.00831198,  0.00947366,
        0.00764093,  0.00692903,  0.0043928 ,  0.00364338,  0.00364338,
        0.00369409,  0.00369409,  0.00412569,  0.00607089,  0.00811352,
        0.00719985,  0.00716047,  0.0059275 ,  0.00716147,  0.00628075,
        0.00749198,  0.00662545,  0.00634642,  0.01172086,  0.01747172,
        0.01049894,  0.00584794,  0.00584794,  0.00494517,  0.00635531,
        0.00635531,  0.00635531,  0.00922528,  0.01267093,  0.02580889,
        0.03458147,  0.02848663,  0.00587979,  0.00506699,  0.00506699,
        0.00347538,  0.00706953,  0.00732246,  0.00639505,  0.006249  ,
        0.00613267,  0.00501122,  0.00461696,  0.00501122,  0.00559165,
        0.00723431,  0.00772963,  0.00867561,  0.01096037,  0.01675656,
        0.01307625,  0.01354239,  0.0147082 ,  0.00916072,  0.00384472,
        0.00384472,  0.00322747,  0.00322747,  0.00347538,  0.00347538,
        0.00322747,  0.00322747,  0.00364871,  0.00533147,  0.00347538,
        0.00347538,  0.00322747,  0.00322747,  0.00322747,  0.00322747,
        0.00322747,  0.00322747,  0.00322747,  0.00360405,  0.00412569,
        0.00471685,  0.00470202,  0.00552461,  0.00940612,  0.00940612,
        0.01199075,  0.00987365,  0.00695446,  0.00695446,  0.00366906,
        0.00937997,  0.01202299,  0.01202299,  0.01202299,  0.01915683,
        0.01876063,  0.01469831,  0.016367  ,  0.016367  ,  0.00384472,
        0.00384472,  0.00369409,  0.00513082,  0.0176742 ,  0.01137985,
        0.0092722 ,  0.00963773,  0.01587638,  0.01903979,  0.01632011,
        0.00779347,  0.01156141,  0.0214587 ,  0.02730376,  0.03285507,
        0.02437772,  0.02740781,  0.02051429,  0.01782488,  0.01848238,
        0.01848238,  0.02875188,  0.02875188,  0.02991737,  0.02695712,
        0.02428545,  0.0206146 ,  0.0206146 ,  0.01524124,  0.00826091,
        0.00692806,  0.00692806,  0.00537412,  0.00556835,  0.00556835,
        0.0050822 ,  0.00419148,  0.00928379,  0.01015865,  0.00928379,
        0.00791169,  0.00822767,  0.01029957,  0.01723299,  0.04708352,
        0.02143951,  0.00472923,  0.00490579,  0.00478565,  0.00468712,
        0.00472692,  0.00416253,  0.00384472,  0.0051242 ,  0.0051242 ,
        0.00600382,  0.00600382,  0.01942654,  0.02515779,  0.03410968,
        0.02795266,  0.02881476]), 'phi_max': 1000, 'E': array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]]), 'phi_0': 2, 'pi_0': 0.01, 'k': 268, 'mu_0': 0.1, 'v': 347}, 'iter': 8, 'init': <function <lambda> at 0x7f29a69e5758>, 'chains': 2}, array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))
WARNING: No variance estimation is
         performed for num_warmup < 20


Iteration: 1 / 8 [ 12%]  (Warmup) (Chain 0)
Iteration: 2 / 8 [ 25%]  (Warmup) (Chain 0)
Iteration: 3 / 8 [ 37%]  (Warmup) (Chain 0)
Iteration: 4 / 8 [ 50%]  (Warmup) (Chain 0)
Iteration: 5 / 8 [ 62%]  (Sampling) (Chain 0)
Iteration: 6 / 8 [ 75%]  (Sampling) (Chain 0)
Iteration: 7 / 8 [ 87%]  (Sampling) (Chain 0)
Iteration: 8 / 8 [100%]  (Sampling) (Chain 0)
#
#  Elapsed Time: 0.012279 seconds (Warm-up)
#                0.005695 seconds (Sampling)
#                0.017974 seconds (Total)
#
WARNING: No variance estimation is
         performed for num_warmup < 20

Iteration: 1 / 8 [ 12%]  (Warmup) (Chain 1)
('DEBUG: The server encountered an unexpected exception: Exception thrown at line 60: Error in function boost::math::tgamma<double>(double): numeric overflow', OverflowError('Exception thrown at line 60: Error in function boost::math::tgamma<double>(double): numeric overflow',))
```

The model is

```
data {
  int<lower=1> v;
  int<lower=1> k;

  vector[v] a;
  matrix[v, k] E;

  real<lower=0> phi_max;  // Hyperparameter for "phi"
  real phi_0;             // Hyperparameter for "mu"
  real mu_0;              // Hyperparameter for "mu"
  real pi_0;              // Hyperparameter for "w_0"
}

parameters {
  real<lower=0, upper=1> mu;
  real<lower=0, upper=phi_max> phi;

  vector[k] w;
  real w_0;
}

transformed parameters {
  real alpha;
  real beta_;
  vector[v] pi;

  // Get the rate and shape from "mu" and "phi" for the beta distribution later
  alpha = phi * mu;
  beta_ = phi - alpha;

  pi = 1 ./ (1 + exp(-(E * w + w_0)));
}

model {
  phi ~ uniform(0, phi_max);
  mu ~ beta(mu_0, phi_0);

  a ~ beta(alpha, beta_);

  w ~ normal(0, 1);
  w_0 ~ normal(logit(pi_0), 1);
}

generated quantities {
  vector[v] c;
  vector[v] likelihoods;
  real normalization_constant;
  real constant;

  normalization_constant = 0;
  constant = (tgamma(phi) / (tgamma(mu * phi) * tgamma((1 - mu) * phi)));
  for (i in 1:v) {
    likelihoods[i] = constant * pow(a[i], (mu * phi - 1)) * pow((1 - a[i]), ((1 - mu) * phi - 1));
    c[i] = likelihoods[i] * pi[i];
    normalization_constant = normalization_constant + c[i];
  }
}
```

Python 2.7.6
```
>>> pystan.__version__
'2.14.0.0'
```

#### Reproducible Steps:
See above

#### Current Output:
See above

#### Expected Output:
I do not really have an expected output, except that the inference should not exit with `Error in function boost::math::tgamma<double>(double): numeric overflow`

#### Additional Information:
Possibly related: (https://github.com/stan-dev/stan/issues/476)

#### Current Version:
v2.14.0

**Comment by sakrejda** [comment] 2017-03-22 18:36
@ariddell Is this enough to run PyStan from? I haven't tried running PyStan (mostly been doing CmdStan)..

**Comment by ptn24** [comment] 2017-03-22 18:38
Note that this does not deterministically exit with `numeric overflow`, perhaps due to the randomness of sampling. I cannot get the actual parameter values that cause the overflow because the process just terminates, but the input data is certainly the same across runs

**Comment by sakrejda** [comment] 2017-03-22 18:57
Thanks for adding the details.

**Comment by ptn24** [comment] 2017-03-22 19:02
Thank you for investigating! Please let me know what you find, or if I am doing something wrong on my end.

**Comment by ariddell** [comment] 2017-03-22 20:09
Can you fix a random seed when you call sampling? I imagine we would need that seed and the data to reproduce. You can also recover the random seed used from the depths of the fit object, but this isn't documented well.

But perhaps this is the expected behavior? If you call tgamma with a value which causes a numeric overflow, shouldn't it raise an exception?

**Comment by sakrejda** [comment] 2017-03-22 20:38
If it happens during sampling it should reject but shouldn't we just return
something sensible on overflow in generated quantities? I think the design
around that was discussed for the binomial RNG recently.

**Comment by bob-carpenter** [comment] 2017-03-22 21:45
I followed the exception behavior tgamma in C99 (and now in the std:: namespace in C++11).  My reasoning was that programs that don't throw exceptions in basic C++ shouldn't throw exceptions when plugging in autodiff types or you might get excepting programs with autodiff types that would complete with double (because you threw away the NaN or infinite result).  See:

http://www.cplusplus.com/reference/cmath/tgamma/

We've talked about changing that behavior to have everything except early and often when arguments are out of bound.  It'd need a pass through all the functions to make sure we do this.  Then the question arises as to whether we want to do the same thing with the double versions, which means dropping them into our own namespace and being careful with qualifications.

**Comment by ptn24** [comment] 2017-03-23 00:30
@ariddell: How do I go about "fixing a random seed"?

What will cause "tgamma" to overflow? For example, do the specified inputs above necessarily elicit an overflow? I also notice from (https://github.com/stan-dev/stan/issues/476) that the sample should just be rejected or something?

**Comment by sakrejda** [comment] 2017-03-23 01:57
@ptn24 Does your model run if you remove the generated quantities block?  If the tgamma call overflows in the density calculation (model and transformed parameters blocks) it will reject but the generated quantities block is not part of that so it doesn't reject.  You can always do the generated quantities calculation as a second step.

Negative integers or large values of x will cause overflow and since this is the Gamma function x need not be very large to cause it to overflow `double` values.  I think this issue is not going to get resolved in the near future because, as @bob-carpenter, mentions there is a slight design issue and making a change will require going through a lot of code.

**Comment by ptn24** [comment] 2017-03-26 05:16
@sakrejda: I lifted the gamma function evaluation into the application layer, and I notice that the overflow is because the variable "constant" (above) is "nan". Here is the stdout log

```
./utils.py:248: RuntimeWarning: invalid value encountered in double_scalars
  constant = (gamma(phi) / (gamma(mu * phi) * gamma((1 - mu) * phi)))
('DEBUG: The server encountered an unexpected exception: The constant term should be a number, but is nan (mu=0.03464174185, phi=502.890817548)', AssertionError('The constant term should be a number, but is nan (mu=0.03464174185, phi=502.890817548)',))
```

What is the best way to proceed? Is it mathematically valid to reject this sample and re-sample?

**Comment by sakrejda** [comment] 2017-03-26 10:36
Nothing that happens in generated quantities affects sampling, but you
can't just throw those values out for inference.  It's probably Nan because
it's too big, so you need an alternative expression.

**Comment by bob-carpenter** [comment] 2017-03-27 17:12
Also, tgamma is prone to overflow---you want to use lgamma
(on the log scale) wherever possible.

- Bob

**Comment by ptn24** [comment] 2017-03-27 20:02
I see. I switched to lgamma, and things seem to be working. Thank you!

**Comment by sakrejda** [comment] 2017-04-11 17:40
I think this is a non-issue or a bigger design issue with how throws in generated quantities are handled.  Either way no straightforward path to a fix.  If you want to re-open solution should be discussed on dev list.

**Closed by sakrejda** 2017-04-11 17:40 UTC

**Comment by bob-carpenter** [comment] 2017-04-11 17:46
See #1943 for the reject in generated quantities issue.  Solving that issue will solve this one.
