### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by Marie-Karelle** [stan-dev/stan#1510] opened 2015-06-22 12:53 UTC
Dear STAN team,

I am using STAN to draw MCMC samples and calculate derivatives of the log-likelihood. I made a first version of my code that was working as expected. Then I extended it to differential equations. While I was testing it, I think I felt on a STAN bug. Indeed, my STAN model compile and seems to execute well (I put a print at the end of the model to check it was ok), but during the sampling, it freezes, and then crashes if I try an action on the R window. (It seems that on Linux, it "only" freezes).

I am using:
R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Platform: x86_64-w64-mingw32/x64 (64-bit)
rstan (Version 2.6.0, packaged: 2015-02-06 21:02:34 UTC, GitRev: 198082f07a60)
created by rstan at Mon Jan 19 19:10:04 2015 
CXXFLAGS = -O3 -Wall $(DEBUGFLAG) -mtune=core2  #set_by_rstan
R_XTRA_CPPFLAGS = -I"$(R_HOME)/include"   #set_by_rstan
The memory is 12151 Mo

I tried to simplify my code as much as possible. I have two STAN models, and one R code.

First STAN model in the file "model_y.stan":
```
functions {
  real[] sho(real t,real[] y,real[] param_rand,real[] x_r,int[] x_i) {
    real dydt[3];
    dydt[1] <- -param_rand[1]*y[1];
    dydt[2] <- param_rand[1]/param_rand[2]*y[1] - param_rand[3]/param_rand[2] * y[2];
    dydt[3] <- param_rand[4]*(1 - y[2]/(param_rand[5]+y[2])) - param_rand[6] * y[3];
    return dydt;
  }
}
data {
  int dim_b;
  int dim_t;
  vector[dim_b] mu_b;
  int nb_t[dim_t];
  matrix[max(nb_t),dim_t] t;
  vector[14] params; 
  real t0;
}
transformed data { 
  vector[dim_b] Omega;
  real times1[nb_t[1]];
  real times2[nb_t[2]];
  real times2_modif[nb_t[2]-1];
  real x_r[0];
  int x_i[0];
  for(i in 1:dim_b){
    Omega[i] <- sqrt(params[7+i-1]);
  }
  times1 <- to_array_1d(segment(col(t,1),1,nb_t[1]));
  times2 <- to_array_1d(segment(col(t,2),1,nb_t[2]));
  times2_modif <- segment(times2,2,nb_t[2]-1);
}
model { 
}
generated quantities {
  vector[dim_b] b;
  real eps[max(nb_t),dim_t];
  real param_rand[dim_b]; 
  real y[max(nb_t),dim_t]; 
  matrix[max(nb_t),dim_t] SdEps;
  matrix[max(nb_t),dim_t] y_hat;
  real y_hat_temp1[nb_t[1],3];
  real y_hat_temp2[nb_t[2],3];
  real y_hat_temp2_modif[nb_t[2]-1,3]; 
  real y0[3];
  
  for(i in 1:dim_b){
    b[i] <- normal_rng(mu_b[i], Omega[i]);
  }
  param_rand <- to_array_1d(segment(params, 1, dim_b) .* exp(b));
  
  y0[1] <- 100;
  y0[2] <- 0;
  y0[3] <- param_rand[4]/param_rand[6];
  y_hat_temp1 <- integrate_ode(sho, y0, t0, times1, param_rand, x_r, x_i);
  if(t0 == times2[1]){
    y_hat_temp2_modif <- integrate_ode(sho, y0, t0, times2_modif, param_rand, x_r, x_i);
  }
  else{
    y_hat_temp2 <- integrate_ode(sho, y0, t0, times2, param_rand, x_r, x_i);
  }
  for(t1 in 1:nb_t[1]){
    y_hat[t1,1] <- y_hat_temp1[t1,2];
    SdEps[t1,1] <- params[13] * y_hat[t1,1];
  }
  if(t0 == times2[1]){
    y_hat[1,2] <- y0[3];
    SdEps[1,2] <- params[14];
    for(t2 in 2:nb_t[2]){
      y_hat[t2,2] <- y_hat_temp2_modif[t2-1,3];
      SdEps[t2,2] <- params[14];
    }
  }
  else{
    for(t2 in 1:nb_t[2]){
      y_hat[t2,2] <- y_hat_temp2[t2,3];
      SdEps[t2,2] <- params[14];
    }
  }

  for(i in 1:dim_t){
    for(id_t in 1:nb_t[i]){
      eps[id_t,i] <- normal_rng(0,SdEps[id_t,i]);
      y[id_t,i] <- y_hat[id_t,i] + eps[id_t,i];
    }
  }
}
```

Second STAN model in the file "Pk_Pd_Warfarin.stan":
```
functions {
  real[] sho(real t,real[] y,real[] param_rand,real[] x_r,int[] x_i) {
    real dydt[3];
    dydt[1] <- -param_rand[1]*y[1];
    dydt[2] <- param_rand[1]/param_rand[2]*y[1] - param_rand[3]/param_rand[2] * y[2];
    dydt[3] <- param_rand[4]*(1 - y[2]/(param_rand[5]+y[2])) - param_rand[6] * y[3];
    return dydt;
  }
}
data {
  int dim_b;
  int dim_t;
  vector[dim_b] mu_b;
  int nb_t[dim_t];
  matrix[max(nb_t),dim_t] t;
  real y[max(nb_t),dim_t]; 
  vector[14] params; 
  real t0;
}
transformed data { 
  vector[dim_b] Omega;
  real times1[nb_t[1]];
  real times2[nb_t[2]];
  real times2_modif[nb_t[2]-1];
  real x_r[0];
  int x_i[0];
  for(i in 1:dim_b){
    Omega[i] <- sqrt(params[7+i-1]);
  }
  times1 <- to_array_1d(segment(col(t,1),1,nb_t[1]));
  times2 <- to_array_1d(segment(col(t,2),1,nb_t[2]));
  times2_modif <- segment(times2,2,nb_t[2]-1);
}
parameters {
  vector[dim_b] b;
}
transformed parameters {
  real param_rand[dim_b];
  param_rand <- to_array_1d(segment(params, 1, dim_b) .* exp(b)); 
}
model { 
  matrix[max(nb_t),dim_t] SdEps;
  matrix[max(nb_t),dim_t] y_hat;
  real y_hat_temp1[nb_t[1],3];
  real y_hat_temp2[nb_t[2],3];
  real y_hat_temp2_modif[nb_t[2]-1,3];
  real y0[3];

  y0[1] <- 100;
  y0[2] <- 0;
  y0[3] <- param_rand[4]/param_rand[6];

  b ~ normal(mu_b, Omega);

  y_hat_temp1 <- integrate_ode(sho, y0, t0, times1, param_rand, x_r, x_i);
  if(t0 == times2[1]){
    y_hat_temp2_modif <- integrate_ode(sho, y0, t0, times2_modif, param_rand, x_r, x_i);
  }
  else{
    y_hat_temp2 <- integrate_ode(sho, y0, t0, times2, param_rand, x_r, x_i);
  }
  for(t1 in 1:nb_t[1]){
    y_hat[t1,1] <- y_hat_temp1[t1,2];
    SdEps[t1,1] <- params[13] * y_hat[t1,1];
  }
  if(t0 == times2[1]){
    y_hat[1,2] <- y0[3];
    SdEps[1,2] <- params[14];
    for(t2 in 2:nb_t[2]){
      y_hat[t2,2] <- y_hat_temp2_modif[t2-1,3];
      SdEps[t2,2] <- params[14];
    }
  }
  else{
    for(t2 in 1:nb_t[2]){
      y_hat[t2,2] <- y_hat_temp2[t2,3];
      SdEps[t2,2] <- params[14];
    }
  }

  for(i in 1:dim_t){
    for(id_t in 1:nb_t[i]){
      y[id_t,i] ~ normal(y_hat[id_t,i],fabs(SdEps[id_t,i]));
    }
  }
print("fini0")
}
```

R code:
```
library(rstan)
library(mvtnorm)
model = stan_model("Pk_Pd_Warfarin.stan")
model3 = stan_model("model_y.stan")
                                         
test_bug = function(model, model3){
  set.seed(42) 
  mat_t = matrix(0,nrow=2,ncol=max(13,8))
  mat_t[1,1:13] = c(0.5,1,2,3,6,9,12,24,36,48,72,96,120)
  mat_t[2,1:8] = c(0,24,36,48,72,96,120,144)
  nb_t=c(13,8)
  params = c(1.6, 7.95, 0.133, 5.41, 1.2, 0.056, 0.701, 0.02, 0.063, 0.19, 0.013, 0.016, 0.2, 3.88) 
  t0 = 0
  dim_b = 6
  n_rep=1
  n_samp=100 
  n_iter=200 
  n_burn=500
  dim_t = nrow(mat_t)
  nb_params = length(params)

  sample_y = array(0,dim=c(n_samp*n_rep, max(nb_t), dim_t))
  data_cur = list(params=params, mu_b=rep(0, dim_b), t=t(mat_t), t0=t0, nb_t=nb_t, dim_b=dim_b, n_rep=n_rep, dim_t=dim_t)
  init_cur  = list(y=0.5, b=rmvnorm(1, mean = rep(0, dim_b), sigma = diag(rep(0.1, dim_b)))[1,])
  temp_sample_y = extract(sampling(model3, data=data_cur, chains=1, init=list(init_cur), warmup=0, iter=n_samp, thin=1, refresh=-1,algorithm="Fixed_param"), permuted=FALSE)

  for(ind_y_samp in 1:n_samp){
    y_samp = temp_sample_y[ind_y_samp,1,which(grepl("y",names(temp_sample_y[1,,]))==TRUE)]
    for(id_dimt in 1:dim_t){
      sample_y[(n_rep*(ind_y_samp-1)+1):(n_rep*ind_y_samp),1:nb_t[id_dimt],id_dimt] = 
            matrix(y_samp[(n_rep*max(cumsum(nb_t)[id_dimt-1],0)+1):(n_rep*cumsum(nb_t)[id_dimt])], nrow=n_rep, ncol=nb_t[id_dimt], byrow=FALSE)
    }
  }
 
  for(ind_y_samp in 1:n_samp){
print(ind_y_samp)
    smp_y = sample_y[(n_rep*(ind_y_samp-1)+1):(n_rep*ind_y_samp),,]
    data_cur = list(y=smp_y, params=params, mu_b=rep(0, dim_b), t=t(mat_t), t0=t0, nb_t=nb_t, dim_b=dim_b, n_rep=n_rep, dim_t=dim_t)
    init_cur = list(b=temp_sample_y[ind_y_samp,1,1:dim_b])
    if(dim_b > 1){
      init_cur2 = list(b=rmvnorm(1, mean = rep(0, dim_b), sigma = diag(rep(0.1, dim_b)))[1,])
    }
    else if(dim_b == 1){
      init_cur2 = list(b=rnorm(1, 0, sqrt(0.1)))
    }

    sample_b_sY = extract(sampling(model, data=data_cur, chains=2, init=list(init_cur, init_cur2), warmup=n_burn, iter=10*n_iter+n_burn, thin=10, refresh=-1), permuted=FALSE)
print("fini 1")  
  }

  return(0)
}

test_bug(model, model3)
```

The first sampling (with model3) is working, it is the second (with model) which freezes.

Thank you very much in advance for your help, and for fixing this issue.
Best regards,

MK Riviere

**Comment by bob-carpenter** [comment] 2015-06-22 19:55
I have a hunch that it's dying in the integrate_ode() call.

Can you see if you still have CPU activity when it's frozen?   And does it get 5 or 10 or 20 iterations in before freezing?  

The problem with the current Stan integrator for ODEs is that if the parameters drift into locations where the equations become stiff, we haven't figured out how to put an upper bound on the number of integration steps.  So the integrator keeps trying to reduce the step size and it seems to freeze (but you'll probably still see plenty of CPU usage).

We have a prototype fitted out with a stiff solver in place (CVODE from Sundials) and that should be coming to Stan soon and fixing this problem if that's what it is.

I have another of these models I need to debug from someone else with roughly the same behavior and I'm going to try to develop some general diagnostics.  

I also want to warn you this may take a while to sort out --- we're slammed with summer conference travel and getting Stan 2.7 out.

**Comment by Marie-Karelle** [comment] 2015-06-23 08:03
Indeed, I have CPU activity when it's frozen. With this seed, it gets 23
iterations before freezing, but with other it can be 1.

Thank you very much for your response. I understand that you must have
plenty of things to do, especially as it seems that STAN is growing and
being more and more used. I will wait and check when you will sort it out.
Thank you again.

Best regards,
MK Riviere



2015-06-22 21:56 GMT+02:00 Bob Carpenter <notifications@github.com>:

**Comment by syclik** [comment] 2015-07-31 02:52
@Marie-Karelle: sorry for the delay. I'm trying out your script and I can't get it working. Would you mind dumping out the data used for the model? Before line 46:
```
stan_rdump(list = names(data_cur), file = "Pk_Pd_Warfarin.data.R", envir = list2env(data_cur))
```
If you can get that file to me, I'll be able to debug it easier.

**Comment by Marie-Karelle** [comment] 2015-07-31 10:13
Thank you for your answer. Please find attached the file you need. Let me
know if you need anything else.

Best regards,
MK Riviere

2015-07-31 4:52 GMT+02:00 Daniel Lee <notifications@github.com>:

**Comment by syclik** [comment] 2015-07-31 10:23
Looks like the attachment didn't make it. Could you email it to me at bearlee@alum.mit.edu or add it add a gist?

**Comment by syclik** [comment] 2015-08-11 13:38
@Marie-Karelle, thanks for sending it to me. I verified that it is stuck, but it hasn't died. It's having trouble with the ode solver, as far as I can tell. I'll try the cause of it for the Stan program and see if we can work around it.

**Comment by bob-carpenter** [comment] 2015-08-11 17:30
Do you have the stiff solver at hand?  I have another problem like
this for the ODE solver for a PK/PD model --- it gets stuck at
iteration 10.  Presumably in the ODE solver because there's nowhere
else for it to get stuck on a single iteration.

- Bob

**Comment by Marie-Karelle** [comment] 2015-11-04 09:27
Hello everyone,

Thank you very much for your hard work on Stan. 

I was wondering, do you know approximately when you will release a new version with a good ODE solver ?
Indeed, we have another project where we would need it, and observed the same freezing issue. Just like to know if I should drop it or if there will be a new version soon.

Thank you very much !
Best

**Comment by bob-carpenter** [comment] 2015-11-04 19:06
Thanks for checking in.  We'd like to keep open-ended discussions on the users list or developers list rather than in a discussion of a specific bug report.  I'm going to reply here and then close this issue.  It'll be solved when we add stiff solvers.

We've actually got working branches with CVODE stiff solvers from the Sundials package working on local branches.   A team at Novartis (NJ group with Xiong, James, He, and Wang) has a branch on their own development that just autodiffs through LSODA that they're building into their PMX package;  see:

http://andrewgelman.com/2015/10/05/pmxstan-an-r-package-to-facilitate-bayesian-pkpd-modeling-with-stan/

We have done more digging and realized that we can't use LSODA for two reasons:  (1) very sketchy license provenance, and (2) it doesn't  let you plug in user-defined Jacobian functions for sensitivities, which we'll need for robustness and accuracy and efficiency. 

The problem we face now is making it portable and making it play nicely with R and Python installs.  It's a colossal pain due to Sundials's old-fashioned C code with no encapsulation of memory, function pointers, non header-only builds, exception handling, and conditional compiles that break Windows installs.  the 

It's high priority, but we're backing away from making promises of when things will be available.  I can pretty much guarantee it won't be available in an official version of Stan until 2016.

**Closed by bob-carpenter** 2015-11-04 19:06 UTC
